- cdp-langchain/poetry.lock
- cdp-langchain/pyproject.toml
- Use released version of `cdp-agentkit-core` as main dep in `cdp-langchain`
> chore: Use Released Version of cdp-agentkit-core as dep in Ext's

- .github/workflows/publish_docs.yml
- API Docs generation GHA: Add step to checkout repo
> fix: GHA Docs Generation - Checkout repo step

- cdp-langchain/cdp_langchain/utils/cdp_agentkit_wrapper.py
- Export agent's wallet default address ID as `default_address_id` on wallet data.
> feat: Export Agentic Wallet Default Address ID

- README.md
- This widget is unused since we will not be using GH releases for the corresponding PyPI releases
> fix: Remove README Release Widget

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/docs/conf.py
- cdp-agentkit-core/pyproject.toml
- cdp-langchain/CHANGELOG.md
- cdp-langchain/docs/conf.py
- cdp-langchain/poetry.lock
- cdp-langchain/pyproject.toml
- release `0.0.2` of `cdp-langchain` and `cdp-agentkit-core`
> chore: Bump version to 0.0.2

- README.md
- twitter-langchain/README.md
- twitter-langchain/poetry.lock
- twitter-langchain/pyproject.toml
- Clean up READMEs
- Release `twitter-langchain` - `0.0.2`
- Bump dep on `cdp-agentkit-core` to `0.0.2`
- Add `standard-imghdr` as a dep - this package was in the Python standard lib until `3.13` so this dep patches broken behavior in `>=3.13`
> Twitter langchain release 0.0.2

- twitter-langchain/poetry.lock
- twitter-langchain/pyproject.toml
- Release `twitter-langchain` version `0.0.3` with bump to `cdp-agentkit-core` `0.0.3`
> chore: release twitter-langchain 0.0.3

- CONTRIBUTING.md
This pull request corrects a common spelling error in two places within the documentation:
The word "receieve" has been changed to "**receive**" to ensure consistency and proper spelling.
This is a minor fix but helps improve the clarity and professionalism of the documentation.
> Typos CONTRIBUTING.md

- cdp-agentkit-core/cdp_agentkit_core/actions/mint_nft.py
The word "receieve" has been changed to "receive" to ensure consistency and proper spelling.
> Typos Update mint_nft.py

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/cdp_agentkit_core/actions/wow/create_token.py
- cdp-agentkit-core/tests/actions/wow/test_create_token.py
Currently all tokens created on wow through this tool have the same token metadata, allow passing custom metadata so people can override things like token image
works case it'd break the tool, seems unlikely
> Add ability to pass in custom metadata for wow token creation

- twitter-langchain/README.md
- twitter-langchain/twitter_langchain/twitter_toolkit.py
> chore: updating docs with the latest twitter actions

- .github/workflows/lint.yml
- twitter-langchain/tests/actions/test_account_details.py
- twitter-langchain/tests/actions/test_account_mentions.py
- twitter-langchain/tests/actions/test_post_tweet.py
- twitter-langchain/tests/actions/test_post_tweet_reply.py
> feat: twitter langchain gha linter

- CONTRIBUTING.md
- README.md
Adding links and minor improvements to README.md copy.
> chore: Updating README.md copy

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- Add GH Issues templates for bug reports and feature proposals
> chore(PSDK-632): Add Github Issues Templates

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/poetry.lock
- cdp-agentkit-core/pyproject.toml
- Bump `@coinbase/cdp-sdk` to `0.13.0`
> chore: bump cdp-agentkit-core deps

- twitter-langchain/CHANGELOG.md
- twitter-langchain/poetry.lock
- twitter-langchain/pyproject.toml
* bump cdp-agentkit-core to 0.0.7
> chore: bump twitter-langchain deps

- cdp-agentkit-core/Makefile
- cdp-langchain/Makefile
- Use `poetry` virtual env to run `pytest` in `make test`
> chore: Use Poetry venv for make test

- README.md
- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/Makefile
- cdp-agentkit-core/cdp_agentkit_core/actions/__init__.py
- cdp-agentkit-core/cdp_agentkit_core/actions/deploy_nft.py
- cdp-agentkit-core/cdp_agentkit_core/actions/get_balance.py
- cdp-agentkit-core/cdp_agentkit_core/actions/mint_nft.py
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/account_details.py
- cdp-agentkit-core/cdp_agentkit_core/actions/transfer.py
- cdp-agentkit-core/cdp_agentkit_core/actions/wow/utils.py
- cdp-agentkit-core/cdp_agentkit_core/actions/wrap_eth.py
- cdp-agentkit-core/tests/actions/test_wrap_eth.py
- cdp-langchain/Makefile
- cdp-langchain/README.md
- cdp-langchain/cdp_langchain/agent_toolkits/cdp_toolkit.py
- cdp-langchain/examples/chatbot/chatbot.py
- Implement `wrap_eth` action 
- Corresponding AgentKit.js PR https://github.com/coinbase/cdp-agentkit-nodejs/pull/56
- Update `make` commands to all use `poetry` virtual env
- `make format && make lint` on all files
> feat: Wrap ETH to WETH on Base Action

- cdp-langchain/CHANGELOG.md
- cdp-langchain/docs/conf.py
- cdp-langchain/poetry.lock
- cdp-langchain/pyproject.toml
- twitter-langchain/CHANGELOG.md
- twitter-langchain/docs/conf.py
- twitter-langchain/poetry.lock
- twitter-langchain/pyproject.toml
- Release `cdp-langchain` `0.0.10` & `twitter-langchain` `0.0.8`
> chore: Release cdp-langchain 0.0.10 & twitter-langchain 0.0.8

- .github/workflows/publish_docs.yml
- README.md
- cdp-agentkit-core/python/docs/index.rst
- cdp-langchain/python/docs/index.rst
- twitter-langchain/python/docs/index.rst
- Fix GH Pages generated Python docs path
> chore: Fix Generated Python Docs Path

- cdp-agentkit-core/typescript/CHANGELOG.md
- cdp-agentkit-core/typescript/src/actions/cdp/get_balance_nft.ts
- cdp-agentkit-core/typescript/src/actions/cdp/index.ts
- cdp-agentkit-core/typescript/src/actions/cdp/transfer_nft.ts
- cdp-agentkit-core/typescript/src/tests/get_balance_nft_test.ts
- cdp-agentkit-core/typescript/src/tests/transfer_nft_test.ts
- cdp-langchain/typescript/src/toolkits/cdp_toolkit.ts
TypeScript port of https://github.com/coinbase/agentkit/pull/103
0. Via chatbot example in `cdp-langchain`
1. Asked Agent to create an NFT collection
2. Asked Agent to mint an NFT from this collection to its wallet
3. Asked Agent to check its balance of this collection
4. Asked Agent to transfer its NFT to another address
5. Asked Agent to check its balance again, then check the balance of the other address
Some excerpts from the chat:
```
Prompt: get your wallet balance for nft address 0xb77B8e8be8C31196a487863184f8Ac9cb2773212
Wallet: 5984d4f6-0d07-4378-b7fa-3354504493fa on network: base-sepolia with default address: 0xb978EE7a8A1F24d1258805F692e47B23Da5aC88B
Address 0xb978EE7a8A1F24d1258805F692e47B23Da5aC88B owns 1 NFTs in …
```
> feat(typescript): add nft transfer and balance actions

- cdp-agentkit-core/python/CHANGELOG.md
- cdp-agentkit-core/python/cdp_agentkit_core/actions/__init__.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/get_balance_nft.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/transfer_nft.py
- cdp-agentkit-core/python/tests/actions/test_get_balance_nft.py
- cdp-agentkit-core/python/tests/actions/test_transfer_nft.py
- cdp-langchain/python/cdp_langchain/agent_toolkits/cdp_toolkit.py
Added two new actions for NFT (ERC721) support:
- TransferNftAction: Transfer NFTs between addresses
- GetBalanceNftAction: Check NFT ownership and balances
These actions enable agents to handle NFT operations similar to existing ERC20 functionality.
> feat: Add NFT transfer and balance actions

- cdp-agentkit-core/python/CHANGELOG.md
- cdp-agentkit-core/python/cdp_agentkit_core/actions/__init__.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/pyth/fetch_price.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/pyth/fetch_price_feed_id.py
- cdp-agentkit-core/python/tests/actions/pyth/test_fetch_price.py
- cdp-agentkit-core/python/tests/actions/pyth/test_fetch_price_feed_id.py
- cdp-agentkit-core/typescript/CHANGELOG.md
- cdp-agentkit-core/typescript/src/actions/cdp/data/pyth/fetch_price.ts
- cdp-agentkit-core/typescript/src/actions/cdp/data/pyth/fetch_price_feed_id.ts
- cdp-agentkit-core/typescript/src/actions/cdp/data/pyth/index.ts
- cdp-agentkit-core/typescript/src/actions/cdp/index.ts
- cdp-agentkit-core/typescript/src/tests/data_pyth_fetch_price_feed_id_test.ts
- cdp-agentkit-core/typescript/src/tests/data_pyth_fetch_price_test.ts
- Added `pyth_fetch_price_feed_id` action to fetch the price feed ID for a given token symbol from Pyth.
- Added `pyth_fetch_price` action to fetch the price of a given price feed from Pyth.
- Python and Typescript implementations
> feat: Pyth Network Price Feed Actions

- cdp-agentkit-core/python/README.md
- cdp-langchain/python/README.md
- cdp-langchain/python/pyproject.toml
- twitter-langchain/python/README.md
- twitter-langchain/python/pyproject.toml
- Add READMEs to Python Package Dirs to Unblock Poetry Publish
- Poetry publish does not support relative paths or symlinks
> chore: Add READMEs to Python Package Dirs to Unblock Poetry Publish

- README.md
- Fixed a broken link pointing to SECURITY.md in the README.md file.
> fix: fix README broken link to SECURITY

- cdp-agentkit-core/python/cdp_agentkit_core/actions/__init__.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/constants.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/create_flow.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/delete_flow.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/update_flow.py
- cdp-agentkit-core/python/tests/actions/superfluid/test_create_flow.py
- cdp-agentkit-core/python/tests/actions/superfluid/test_delete_flow.py
- cdp-agentkit-core/python/tests/actions/superfluid/test_update_flow.py
- Add action `superfluid_create_flow` to create a flow using Superfluid
- Add action `superfluid_update_flow` to update a flow using Superfluid
- Add action `superfluid_delete_flow` to delete a flow using Superfluid
> feat: add Superfluid flow management actions (create, update, delete)

- cdp-agentkit-core/python/cdp_agentkit_core/actions/__init__.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/address_reputation.py
- cdp-agentkit-core/python/tests/actions/test_address_reputation.py
- cdp-agentkit-core/typescript/src/actions/cdp/address_reputation.ts
- cdp-agentkit-core/typescript/src/actions/cdp/index.ts
- cdp-agentkit-core/typescript/src/tests/address_reputation_test.ts
* adding address_reputation action
*Python*
```
Prompt: what is my address reputation?
Wallet: fee44ff6-5c9f-4c5d-9533-ccfecc2a74b6 on network: base-mainnet with default address: 0x3585680390380941716f012422F7ff6e74A03006
Address Reputation: (score=14, metadata=(total_transactions=4, unique_days_active=3, longest_active_streak=2, current_active_streak=0, activity_period_days=78, token_swaps_performed=3, bridge_transactions_performed=0, lend_borrow_stake_transactions=0, ens_contract_interactions=0, smart_contract_deployments=0))
Your address reputation is as follows:
- **Score:** 14
- **Total Transactions:** 4
- **Unique Days Active:** 3
- **Longest Active Streak:** 2 days
- **Current Active Streak:** 0 days
- …
```
> feat: address reputation

- cdp-agentkit-core/python/cdp_agentkit_core/actions/wow/buy_token.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/wow/create_token.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/wow/sell_token.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/wrap_eth.py
- cdp-agentkit-core/typescript/src/actions/cdp/defi/wow/actions/buy_token.ts
- cdp-agentkit-core/typescript/src/actions/cdp/defi/wow/actions/create_token.ts
- cdp-agentkit-core/typescript/src/actions/cdp/defi/wow/actions/sell_token.ts
- cdp-agentkit-core/typescript/src/actions/cdp/wrap_eth.ts
> fix: correct typo in base mainnet description across multiple files

- cdp-agentkit-core/python/cdp_agentkit_core/actions/social/twitter/post_tweet_reply.py
- cdp-langchain/python/README.md
- farcaster-langchain/examples/chatbot-typescript/chatbot.ts
- twitter-langchain/examples/chatbot-python/chatbot.py
- twitter-langchain/examples/chatbot-typescript/chatbot.ts
1. Fixed typo in `post_tweet_reply.py`: Corrected "reponse" to "response."
2. Corrected "Tookit" to "Toolkit" in `README.md`.
3. Fixed spelling in TypeScript and Python chatbot examples: "informaton" to "information."
4. Standardized descriptions and improved clarity in `chatbot.ts` and `chatbot.py`.
The changes were made to correct spelling errors that could cause confusion and improve the overall clarity and professionalism of the documentation and code comments.
These fixes primarily affect the readability of the documentation and code comments. If the error remained, users or developers reading the documentation might be confused by the incorrect spelling. The errors have been corrected to ensure the text is clear and professional.
> Fix typos in documentation and сode files

- package-lock.json
- twitter-langchain/python/CHANGELOG.md
- twitter-langchain/python/docs/conf.py
- twitter-langchain/python/poetry.lock
- twitter-langchain/python/pyproject.toml
- twitter-langchain/typescript/CHANGELOG.md
- twitter-langchain/typescript/package.json
* bumped cdp-agentkit-core  to 0.0.11 for python
* bumped cdp-agentkit-core  to 0.0.14 for typescript
* release python twitter-langchain 0.0.11
* release typescript twitter-langchain 0.0.12
> chore: release twitter-langchain

- .github/workflows/publish_npm_farcaster_langchain.yml
Adds action to publish farcaster-langchain
> chore: add github action to publish farcaster-langchain

- .github/CONTRIBUTING.md
Closes action item: Articulate on how to work with monorepos generally, and what defines a package
> chore: describe monorepo setup in contributing guide

- .github/CONTRIBUTING-PYTHON.md
- .github/CONTRIBUTING-TYPESCRIPT.md
Closes the action items:
* Articulate subfolder structure – If action falls under one of the predefined categories, it should go under one of the subfolders (e.g. pyth, defi, social)
* Link out to Zod & Pydantic docs
* Add guidance on contributing to new AI frameworks
> chore: add more detail to contributing action guides

- cdp-agentkit-core/typescript/src/action_providers/basename/basenameActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/basename/basenameActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/basename/constants.ts
- cdp-agentkit-core/typescript/src/action_providers/basename/index.ts
- cdp-agentkit-core/typescript/src/action_providers/basename/schemas.ts
Migrate basename action and unit tests
Ran unit tests locally with
```
npx jest src/action_providers/basename/basenameActionProvider.test.ts
```
Tested e2e with this script:
```ts
if (require.main === module) {
(async () => {
const privateKey = process.env.TEST_PRIVATE_KEY as Hex;
const account = privateKeyToAccount(privateKey);
console.log("account address", account.address);
const walletClient = createWalletClient({
account,
chain: baseSepolia,
transport: http(),
});
const wallet = new ViemWalletProvider(walletClient);
const basename = basenameActionProvider();
try {
const result = await basename.register(wallet, {
amount: "0.0001",
basename: "test-basename",
});
console.log(result);
} catch (error) {
console.log("error", error);
}
})();
}
```
Ran:
```
npx ts-node …
```
> chore: migrate basename action

- cdp-agentkit-core/typescript/src/action_providers/weth/constants.ts
- cdp-agentkit-core/typescript/src/action_providers/weth/schemas.ts
- cdp-agentkit-core/typescript/src/action_providers/weth/wethActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/weth/wethActionProvider.ts
> chore: migrate wrap eth action

- cdp-agentkit-core/typescript/src/action_providers/index.ts
- cdp-agentkit-core/typescript/src/action_providers/wallet/README.md
- cdp-agentkit-core/typescript/src/action_providers/wallet/index.ts
- cdp-agentkit-core/typescript/src/action_providers/wallet/walletActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/wallet/walletActionProvider.ts
- cdp-langchain/examples/chatbot-typescript/chatbot.ts
- Migrate `get_wallet_details` action to Action provider paradigm
> chore: migrate get wallet details

- cdp-agentkit-core/typescript/src/action_providers/farcaster/farcasterActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/farcasterActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/schemas.ts
- cdp-agentkit-core/typescript/src/action_providers/index.ts
- cdp-agentkit-core/typescript/src/action_providers/twitter/index.ts
- cdp-agentkit-core/typescript/src/action_providers/twitter/schemas.ts
- cdp-agentkit-core/typescript/src/action_providers/twitter/twitterActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/twitter/twitterActionProvider.ts
- cdp-langchain/examples/chatbot-typescript/chatbot.ts
> 0.1.0(ts): twitter actions

- .eslintrc.base.json
- cdp-langchain/examples/chatbot-typescript/chatbot.ts
- package-lock.json
- package.json
* Enforces all imports to be at the top of the file
* Also removes twitter from cdp-langchain chatbot example
> chore: eslint enforce import order

- cdp-agentkit-core/typescript/src/action_providers/action_provider.ts
- cdp-agentkit-core/typescript/src/action_providers/basename/basenameActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/erc20ActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/erc721ActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/farcasterActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/morpho/morphoActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/twitter/twitterActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/wallet/walletActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/weth/wethActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/wow/wowActionProvider.ts
- cdp-agentkit-core/typescript/src/network/index.ts
- cdp-agentkit-core/typescript/src/network/network.ts
- cdp-agentkit-core/typescript/src/network/types.ts
- cdp-agentkit-core/typescript/src/wallet_providers/cdp_wallet_provider.ts
- cdp-agentkit-core/typescript/src/wallet_providers/viem_wallet_provider.ts
- cdp-agentkit-core/typescript/src/wallet_providers/wallet_provider.ts
Map chainId to networkId so CDP actions can work, specifically testing faucet
> chore: map chainId to networkId

- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/schemas.ts
- cdp-agentkit-core/typescript/src/wallet_providers/cdp_wallet_provider.ts
* deploy nft
[x] local chatbot w/cdp wallet
```
Prompt: can you deploy a random nft?
Deployed NFT Collection RandomNFTCollection:
- to address 0x88f04aC9137c4CAc44bEED9E3A2c0167B2514f99
- on network base-sepolia.
Transaction hash: 0x50c35c641d3e734e415b20541d2bcdf75378e7dd911ee2461fa5c3dee7b6e78e
Transaction link: https://sepolia.basescan.org/tx/0x50c35c641d3e734e415b20541d2bcdf75378e7dd911ee2461fa5c3dee7b6e78e
The NFT collection "RandomNFTCollection" has been successfully deployed. Here are the details:
- Contract Address: [0x88f04aC9137c4CAc44bEED9E3A2c0167B2514f99](https://sepolia.basescan.org/address/0x88f04aC9137c4CAc44bEED9E3A2c0167B2514f99)
- Network: base-sepolia
- Transaction Hash: …
```
> 0.1.0(ts): deploy nft

- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpApiActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpApiActionProvider.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpWalletActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpWalletActionProvider.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/index.ts
Splits CDP Wallet and CDP API actions so that non-CDP Wallet users can consume CDP API actions like faucet and address reputation.
> chore: split out cdp wallet and cdp api actions

- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpApiActionProvider.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpWalletActionProvider.ts
- cdp-langchain/examples/chatbot-typescript/chatbot.ts
* Action Provider name changed
* Need to pass through CDP API keys
> chore: cdpApiActionProvider usage

- cdp-agentkit-core/typescript/src/action-providers/actionDecorator.ts
Fixes this error:
```
Error: 400 Invalid 'tools[0].function.name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'.
```
> fix: use prefix notation that plays nicely with langchain

- cdp-agentkit-core/typescript/src/action-providers/customActionProvider.ts
- cdp-agentkit-core/typescript/src/action-providers/index.ts
- cdp-agentkit-core/typescript/src/agentkit.ts
Adds ability for devs to easily add a custom action provider:
```ts
const custom = customActionProvider<EvmWalletProvider>({
name: "custom_action",
description: "This action does XYZ cool thing",
schema: z.object({
arg1: z.string(),
arg2: z.string(),
}),
invoke: async (walletProvider, args: any) => {
const { arg1, arg2 } = args;
const address = walletProvider.getAddress();
return `Invoked with ${arg1} and ${arg2} from ${address}`;
},
});
const agentKit = await AgentKit.from({
walletProvider,
actionProviders: [custom],
});
```
> feat: support custom action provider

- package-lock.json
- update `package-lock.json` to use published packages in `0.1.0` typescript examples
> chore: Use published packages in 0.1.0 examples

- README.md
The pervious `agentkit/python/cdp-langchain/examples/chatbot-python` directory is no longer there and the folder location is updated
> Fix python example link

- CONTRIBUTING-PYTHON.md
disambuguates -> disambiguates
> docs: update CONTRIBUTING-PYTHON.md

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/alchemy/README.md
- typescript/agentkit/src/action-providers/alchemy/alchemyTokenPricesActionProvider.test.ts
- typescript/agentkit/src/action-providers/alchemy/alchemyTokenPricesActionProvider.ts
- typescript/agentkit/src/action-providers/alchemy/index.ts
- typescript/agentkit/src/action-providers/alchemy/schemas.ts
- typescript/agentkit/src/action-providers/index.ts
Added [Alchemy Prices API](https://docs.alchemy.com/reference/get-token-prices-by-symbol) to Action Providers so agent can get real-time price for 1000+ tokens by market cap either through token symbol (ex, ETH, BTC) or contract address. This provides near-instant responses however the user has to use their `ALCHEMY_API_KEY`.
---
---
> add alchemy prices api to typescript action providers

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/basename/basenameActionProvider.ts
- typescript/agentkit/src/action-providers/erc20/erc20ActionProvider.ts
- typescript/agentkit/src/action-providers/erc721/erc721ActionProvider.ts
- typescript/agentkit/src/action-providers/morpho/morphoActionProvider.ts
- typescript/agentkit/src/action-providers/weth/wethActionProvider.ts
- typescript/agentkit/src/action-providers/wow/wowActionProvider.ts
- Fixed `ActionProvider<...>`  type extensions to include template type argument
> chore: Add explicit template type args for ActionProvider<...> ext

- package.json
The old repository url `https://github.com/coinbase/cdp-agentkit-nodejs` in the `package.json` has been changed to the new one `https://github.com/coinbase/agentkit`. As simple as that.
No or minimal impact to the users. The impact can only be noticeable if the entire monorepo gets published to NPM, or in some Github analytic/statistic tools.
> chore: Updated the repository field in the package.json

- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
Basically a typo
Tested with:
```python
if __name__ == "__main__":
w3 = Web3()
private_key = os.environ.get("PRIVATE_KEY")
assert private_key is not None, "You must set PRIVATE_KEY environment variable"
assert private_key.startswith("0x"), "Private key must start with 0x hex prefix"
account: LocalAccount = Account.from_key(private_key)
w3.middleware_onion.inject(SignAndSendRawMiddlewareBuilder.build(account), layer=0)
print(f"Your hot wallet address is {account.address}")
wallet = EthAccountWalletProvider(
config=EthAccountWalletProviderConfig(
private_key=private_key,
rpc_url="https://sepolia.base.org",
chain_id=84532,
)
)
print(wallet.read_contract(
contract_address=Web3.to_checksum_address("0x4200000000000000000000000000000000000006"),
abi=ERC20_ABI,
function_name="balanceOf", …
```
> fix: use HTTPProvider

- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
CDPWalletProvider.sendTransaction was missing the signature for Server-Signers wallets.
Now the CDPWalletProvider can be used for Server-Signers wallets to send custom contract calls.
> PayloadSignature.wait for Server-Signers

- typescript/agentkit/src/action-providers/moonwell/constants.ts
- typescript/agentkit/src/action-providers/moonwell/index.ts
- typescript/agentkit/src/action-providers/moonwell/moonwellActionProvider.test.ts
- typescript/agentkit/src/action-providers/moonwell/moonwellActionProvider.ts
- typescript/agentkit/src/action-providers/moonwell/schemas.ts
This PR adds adapters to allow users to mint and redeem on Moonwell mToken markets on Base and Base Sepolia.
There are no downstream effects of these changes as this is an isolated change. If there are failures, these changes can be backed out by deleting the `typescript/agentkit/src/action-providers/moonwell` directory.
> Add Moonwell Capabilities

- typescript/agentkit/src/wallet-providers/viemWalletProvider.ts
One-liner: viem's chainId is a number, [agentkit expects a string ](https://github.com/coinbase/agentkit/blob/master/typescript/agentkit/src/network/types.ts#L18)
Avoids potential footgun when action providers are checking networks e.g. [in this line](https://github.com/coinbase/agentkit/blob/master/typescript/agentkit/src/agentkit.ts#L74)
> fix: viem chainId from number to string

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/cdp/cdpApiActionProvider.ts
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/moonwell/moonwellActionProvider.ts
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
- Update unreleased changelog
- Add correlation header data to CDP SDK constructor 
- Export `moonwellActionProvider`
> chore: Prepare 0.1.2 AgentKit.js Release

- python/coinbase-agentkit/coinbase_agentkit/action_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
Tested with:
```
import os
from eth_account import Account
from web3 import Web3
from coinbase_agentkit.wallet_providers import EthAccountWalletProvider
from coinbase_agentkit.wallet_providers.eth_account_wallet_provider import (
EthAccountWalletProviderConfig,
)
private_key = os.environ.get("PRIVATE_KEY")
assert private_key is not None, "You must set PRIVATE_KEY environment variable"
assert private_key.startswith("0x"), "Private key must start with 0x hex prefix"
account = Account.from_key(private_key)
print(account.address)
wallet_provider = EthAccountWalletProvider(
EthAccountWalletProviderConfig(
private_key=private_key, rpc_url="https://mainnet.base.org", chain_id=8453
)
)
hash = wallet_provider.send_transaction(
{
"from": account.address,
"to": …
```
> chore: add web3.py transaction gas fee estimation

- python/coinbase-agentkit/coinbase_agentkit/action_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/constants.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/morpho_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/utils.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
- python/coinbase-agentkit/tests/test_morpho_action_provider.py
This PR
* Migrates Morpho deposit/withdraw
* Makes a small change to `EthAccountWalletProvider#send_transaction` to have more reliable gas estimation
While it's possible to use Web3.py Contract to perform contract interactions, I'm opting to rely more on the standard methods (`send_transaction`) to keep the wallet provider interface generic.
This was tested with the following script:
```python
import os
from eth_account import Account
from eth_account.signers.local import LocalAccount
from web3 import Web3
from coinbase_agentkit.action_providers.morpho.morpho_action_provider import morpho_action_provider
from coinbase_agentkit.wallet_providers import (
EthAccountWalletProvider,
EthAccountWalletProviderConfig,
)
if __name__ == "__main__":
private_key = os.environ.get("PRIVATE_KEY")
assert …
```
> chore: migrate morpho actions

- python/coinbase-agentkit/coinbase_agentkit/action_providers/action_decorator.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/action_provider.py
- python/coinbase-agentkit/pyth_price_example.py
This PR
* Fixes action decorator by calling the wrapper method to register actions, and updating the invoke lambda to pass through the provider argument to the `invoke` call
* Updated the pyth example with the correct action ordering
* Silences Pydantic warning about shadowing `schema`
```
poetry run python pyth_price_example.py
BTC Price Feed ID: e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43
Current BTC Price: $97302.07
```
> chore: fix python action decorator

- CONTRIBUTING-PYTHON.md
This pull request includes a small change to the `CONTRIBUTING-PYTHON.md` file. The change updates the path for the `cdp-langchain` dependency to ensure it points to the correct directory.
* [`CONTRIBUTING-PYTHON.md`](diffhunk://#diff-32aba84783588bcd1b0985a7581b0f2c96f8ba45c22142683ec24cfebc437df5L232-R232): Updated the `cdp-langchain` dependency path to `../../cdp-langchain` for proper resolution.
It would help people who are setting up python code and attract more contributor
> fix: update cdp-langchain path in CONTRIBUTING-PYTHON.md

- python/examples/langchain-cdp-chatbot/chatbot.py
* ensure (py) chatbot has the same action providers as (ts) chatbot
cherry picking:
cdp wallet trade
```
- Address: 0x349002E7213E7F7CF68a8368ca83Fd85CEC4DDB0
- Network:
* Network ID: base-mainnet
* Chain ID: 8453
- Native Balance: 18648725318222
Traded 0.000001 of eth for 0.002654 of usdc.
Transaction hash for the trade: 0x661c9e477f64d495a9a17b61ca503e855c00ce33c0fb4e1a3579e450b90c4228
Transaction link for the trade: https://basescan.org/tx/0x661c9e477f64d495a9a17b61ca503e855c00ce33c0fb4e1a3579e450b90c4228
I successfully traded 0.000001 ETH for 0.002654 USDC. 
- **Transaction Hash:** …
```
> 0.1.0(py): ensure chatbot action provider parity with (ts)

- python/coinbase-agentkit/coinbase_agentkit/network/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/network/chain_definitions.py
- python/coinbase-agentkit/coinbase_agentkit/network/network.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_api_address_reputation_action.py
- python/coinbase-agentkit/tests/action_providers/wallet/conftest.py
Adds network mappings to easily map from network_id to chain_id and chain data.
Testing locally with chatbot:
```
Prompt: what network are you on
- Address: 0x234d74b45c3A942E425363C9C491C3C3B1A80986
- Network:
- Native Balance: 0
I am on the Base Sepolia network.
```
> chore: add network mappings

- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/cdp_wallet_action_provider.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_cdp_wallet_action_provider.py
* Calls get_network instead of accessing network_id directly off cdp_wallet_provider
> chore: fix deploy nft

- README.md
The new `coinbase-agentkit` PyPi package stats are not up yet, so removing the badge for now.
> chore: temp rm pypi badge

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/README.md
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/evm_wallet_provider.py
*This PR is recreating #361 in Python*
* Exposed gas configuration during wallet provider creation
Users were requesting the ability to control gas estimations.
The two main benefits for users are:
1. Reduce `Out of Gas` failures by increasing the gas limit.
2. Speed up the rate a transaction will be picked up by increasing the fee per gas price.
LLM: gpt-4o-mini
Prompt: "Transfer 1 ERC20 token of contract 0x04Ce21CCf093BeC08F4aaF89E1859A67c88f8fc2 to the receiver 0x7Af173A33786C26f92D325c3522F4fB434351b7F"
Configurations for each test:
`gas: undefined` -> [Txn: 42k gas limit, 0.001 max gwei, 0.001 max priority gwei](https://sepolia.basescan.org/tx/0xe80af72ec8ba45a78616c70c87d73f858f0a9632b8f5d872cadb70a49c821497)
`gas: { gas_limit_multiplier: 2 }` -> [Txn: 69k gas limit, 0.001 max gwei, …
> Added GasConfig parameter & usage in CdpWalletProvider/EthAccountWalletProvider

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/network/svm.ts
- typescript/agentkit/src/wallet-providers/solanaKeypairWalletProvider.ts
*Once #385 is merged, this PR will be rebased, I will merge together the updated `SolanaKeypairWalletProvider`, and then publish the PR for review*
Added `SolanaKeypairWalletProvider.fromNetwork` to construct a `SolanaKeypairWalletProvider` with default RPC url's based on the provided network.
To allow users to more easily get started without supplying their own RPC url.
SVM
SolanaKeypairWalletProvider
Solana has not been in the readme. I would delay this until we're closer to completion.
*Will do after #385  is merged*
`SolanaKeypairWalletProvider.fromNetwork('solana-mainnet', privateKey)`
```
Prompt: What is your network?
- Provider: solana_keypair_wallet_provider
- Address: 5RGNssB9BY1kmZDHUWZtVnYpZpV4JzzwqmbX4orYBh4s
- Network: 
* Protocol Family: …
```
> feat: added fromNetwork function to SolanaKeypairWalletProvider

- typescript/agentkit/src/wallet-providers/solanaKeypairWalletProvider.ts
- typescript/agentkit/src/wallet-providers/svmWalletProvider.ts
* Adding this standard Solana method. Will be used by incoming Privy Solana Wallet
* Also renamed `waitForReceipt` to `getSignatureStatus`, following the [docs](https://solana-labs.github.io/solana-web3.js/classes/Connection.html#getsignaturestatus)
Solana
> feat: add signAndSendTransaction

- typescript/agentkit/src/wallet-providers/privyEvmWalletProvider.ts
- typescript/agentkit/src/wallet-providers/privyWalletProvider.ts
This PR simply renames `PrivyWalletProvider` to `PrivyEvmWalletProvider` in preparation for a new `PrivySolanaWalletProvider`. It also adds a new `PrivyWalletProvider` which acts as a factory to generate either a `PrivyEvmWalletProvider`, or (in a following PR) a `PrivySolanaWalletProvider`. This factory is backwards compatible with the existing `PrivyWalletProvider` API.
Tested by running the existing privy chatbot example and verifying via the wallet details action:
```
Prompt: print wallet details
- Provider: privy_evm_wallet_provider
- Address: 0x7a4b9B89C24c0acf3c4Ef5636755DBa908DB3bC2
- Network:
- Native Balance: 0 WEI
Here are the wallet details:
- …
```
> chore: rename privy evm wallet provider

- typescript/agentkit/src/wallet-providers/privyEvmWalletProvider.ts
- typescript/agentkit/src/wallet-providers/privyShared.ts
This PR extracts Privy initialization code so that it can be used in `PrivyEvmWalletProvider` as well as the soon to be added `PrivySolanaWalletProvider`.
Tested by running the existing privy chatbot example and verifying via the wallet details action:
```
Prompt: print wallet details
- Provider: privy_evm_wallet_provider
- Address: 0x7a4b9B89C24c0acf3c4Ef5636755DBa908DB3bC2
- Network:
- Native Balance: 0 WEI
Here are the wallet details:
- **Provider**: privy_evm_wallet_provider
- **Address**: 0x7a4b9B89C24c0acf3c4Ef5636755DBa908DB3bC2
- **Network**:
- Protocol Family: EVM
- Network ID: base-sepolia
- Chain ID: 84532
- **Native Balance**: 0 WEI
```
> chore: extract shared privy types and functions

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/morpho_action_provider.py
Fixed Morpho `deposit` and `withdraw` function headers to conform to the Action Provider Paradigm.
Resolves: #405
N/A
N/A
I was going to make a yield optimizer agent example with Morpho and Compound but Morpho action was not working.
> fix: Morpho python action provider function headers

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/cdp/cdpApiActionProvider.ts
- typescript/agentkit/src/action-providers/cdp/cdpWalletActionProvider.ts
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
- typescript/examples/langchain-cdp-chatbot/chatbot.ts
- typescript/examples/langchain-farcaster-chatbot/chatbot.ts
- typescript/examples/langchain-twitter-chatbot/chatbot.ts
CDP_API_KEY_PRIVATE_KEY new-line parsing was being done in the chatbots, rather than in the CDP classes themselves. This meant new chatbot examples did not inherently work with CDP tooling unless you were aware of this quirk.
To create a better devx
All that use CDP tools
1. Removed parsing in chatbots, consistently received the error as expected
2. Moved parsing into CDP classes, built, pointed chat bots to import from agents and ran. No errors, worked perfectly
> fix: move CDP_API_KEY_PRIVATE_KEY parsing into CDP classes

- typescript/agentkit/README.md
Privy does not support API management of authorization keys yet, just through the dashboard.
> docs: clarify Privy authorization key management

- typescript/examples/langchain-privy-chatbot/chatbot.ts
Fixes a bug where Privy example chatbot always creates a new wallet even when wallet_data.txt exists
Tested by:
1. Running the chatbot and printing wallet
2. Quitting the chatbot
3. Running the chatbot again and checking the wallet is the same
> chore: restore privy solana wallet in chatbot example

- typescript/examples/langchain-privy-chatbot/chatbot.ts
Fixes an issue where devs using Privy Solana chatbot get a warning about `CHAIN_ID` falling back to `base-sepolia`, which is odd since they are using Solana.
> chore: warn on chain id only in privy evm config

- typescript/agentkit/src/action-providers/alchemy/alchemyTokenPricesActionProvider.ts
- typescript/agentkit/src/action-providers/cdp/cdpWalletActionProvider.test.ts
- typescript/agentkit/src/action-providers/cdp/cdpWalletActionProvider.ts
- typescript/agentkit/src/action-providers/erc20/erc20ActionProvider.test.ts
- typescript/agentkit/src/action-providers/erc20/erc20ActionProvider.ts
- typescript/agentkit/src/action-providers/farcaster/farcasterActionProvider.test.ts
- typescript/agentkit/src/action-providers/farcaster/farcasterActionProvider.ts
- typescript/agentkit/src/agentkit.ts
- typescript/examples/langchain-privy-chatbot/chatbot.ts
A lot of the action providers have a naive filter for network:
```
supportsNetwork = () => true;
```
This breaks down now that we have support for Solana.
This PR:
* updates all action providers to filter properly.
* adds a warning when using unsupported actions
Tested with agent by adding these lines to the privy chatbot:
```
const actions = agentkit.getActions();
console.log(actions.map(action => action.name));
```
Before:
```
[
'PythActionProvider_fetch_price_feed',
'PythActionProvider_fetch_price',
'WalletActionProvider_get_wallet_details',
'WalletActionProvider_native_transfer',
'ERC20ActionProvider_get_balance',
'ERC20ActionProvider_transfer',
'CdpApiActionProvider_address_reputation',
'CdpApiActionProvider_request_faucet_funds',
'SplActionProvider_get_balance', …
```
> fix: properly filter network-specific actions

- .github/workflows/publish_nightly.yml
- README.md
- python/examples/langchain-cdp-chatbot/pyproject.toml
- python/examples/langchain-twitter-chatbot/pyproject.toml
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
Adds a nightly build workflow that will automatically publish all packages under development tags (e.g. `nightly` for NPM and `dev` for PyPi).
> chore: add nightly build

- python/coinbase-agentkit/README.md
- typescript/agentkit/README.md
include network id parameter within mnemonic phrase import
> chore: readme mnemonic phrase import updates

- .github/workflows/publish_nightly.yml
- README.md
Fixing package publishing, improving release notes with hyperlink to published packages
The action has been updated to handle publishing multiple nightly builds in one day. This likely won't come up much in practice, but has been useful at least in developing this action.
This PR also updates to README.md to correct the poetry install command, and to add some additional info.
> chore: fix publish_nightly

- typescript/create-onchain-agent/templates/next/package.json
Missing dependencies in CLI template
Needed for non-dev machines who have never used these libraries before to effectively pull them and get started.
> fix: missing dependencies in ts cli template

- package-lock.json
- typescript/create-onchain-agent/package.json
Hotfix to `typescript/create-onchain-agent` for #448 requires a bump & republishing
> bump: release 0.1.3 hotfix

- .github/workflows/publish_pypi_create_onchain_agent.yml
Adds GHA for publishing `create-onchain-agent` package to PyPI.
> feat: Publish create-onchain-agent PyPI GHA

- python/create-onchain-agent/CHANGELOG.md
- python/create-onchain-agent/create_onchain_agent/cli.py
- python/create-onchain-agent/pyproject.toml
- python/create-onchain-agent/templates/chatbot/chatbot.py.jinja
The `pipx run create-onchain-template` fails because the `TEMPLATE_DIR` the CLI was reading from is not bundled with the cli.
Temp fix is to read from github main directly. Fast follow with either:
1. Sticking to Github, start tagging releases better, and whenever we bump the CLI, we update the github tag we pull from to the one we're about to release.
2. Find a way to include the template in the cli build directly
CLI is not building, EthDenver starts today.
Manually tested via deleting the local template directory to ensure it isn't reading that, and then running:
```
poetry install
poetry build
poetry run create-onchain-agent
```
I want to discuss a better way to do this in a fast-follow. There is two flaws with this approach.
1. The CLI slows down slightly, since we're adding a …
> fix: cli tool does not bundle template, but must read them

- python/create-onchain-agent/CHANGELOG.md
- python/create-onchain-agent/poetry.lock
- python/create-onchain-agent/pyproject.toml
Added cli.py missing dependencies to the pyproject.toml
When running the CLI fresh, we get the error:
```
carsonroscoe@MWWFC7DW3K Github % pipx run create-onchain-agent
Traceback (most recent call last):
File "/Users/carsonroscoe/.local/pipx/.cache/69d9ac38d65d20a/bin/create-onchain-agent", line 5, in <module>
from create_onchain_agent.cli import create_project
File "/Users/carsonroscoe/.local/pipx/.cache/69d9ac38d65d20a/lib/python3.13/site-packages/create_onchain_agent/cli.py", line 8, in <module>
import requests
ModuleNotFoundError: No module named 'requests'
```
This is because I added cli.py dependencies to #452 but did not `poetry add` them into the `pyproject.toml`
> fix: python cli was missing core dependencies

- python/create-onchain-agent/CHANGELOG.md
- python/create-onchain-agent/README.md
- python/create-onchain-agent/create_onchain_agent/cli.py
- python/create-onchain-agent/pyproject.toml
The `pipx run create-onchain-agent` works, as long as your `pipx` is running `python` version `3.10` or `3.11`.
You can verify via `pipx run --verbose create-onchain-agent` what your installation is. 
This PR ensures that, when the CLI is called, version `3.10` or `3.11` are calling it. Otherwise, it exits early with a informative response.
The reason for this restriction is:
> Starting with Python 3.12+, Python enforces a new "externally managed environment" restriction. This prevents tools like pipx from properly resolving and installing dependencies in certain system-managed environments.
> fix: improve error handling invalid python version

- .github/workflows/publish_npm_create_onchain_agent.yml
New Github Action
The new npm module `create-onchain-agent` lacks a github action for CI/CD releases.
> feat: added gha for npm create-onchain-agent

- package-lock.json
- typescript/create-onchain-agent/package.json
Added repository to `create-onchain-agent`'s package.json to reflect back on this github repository. This check is needed for provenance.
Also updated the author and licence of package.json to reflect this repo's defaults.
Github action threw this error:
```
npm error 422 Unprocessable Entity - PUT https://registry.npmjs.org/create-onchain-agent - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/coinbase/agentkit" from provenance
```
> chore: fix package.json

- package-lock.json
- typescript/create-onchain-agent/CHANGELOG.md
- typescript/create-onchain-agent/package.json
Added changelog to `typescript/create-onchain-agent`
The changelog is important, and it was missing.
It was also added to test out the github action, as this will bump us to version 0.1.4
> chore: added changelog to create-onchain-agent

- python/coinbase-agentkit/README.md
Spotted during ETH Denver, the `Network` import wasn't working
> fix(docs/python): Fix wrong Network import

- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc20/erc20_action_provider.py
Sometimes the address given by explorers/wallets isn't in the right format, if copied from a URL for example.
This leads to the action giving the following response when called:
```
Error getting balance: ('web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.to_checksum_address(lower_case_address).', '0xc0fbc4967259786c743361a5885ef49380473dcf')
```
In the case of a Base mainnet contract here.
This can easily be fixed by (as explained by the error message) wrapping the address with `Web3.to_checksum_address()`
Issue encountered during ETH Denver
LLM: Nous Hermes 3 Pro
Prompt: `What's your balance of …
> fix(python/erc20-get-balance-action): Converting contract address to checksum to avoid errors

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc20/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc20/constants.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc20/erc20_action_provider.py
- python/coinbase-agentkit/tests/action_providers/erc20/conftest.py
- python/coinbase-agentkit/tests/action_providers/erc20/test_erc20_action_provider.py
We were not formatting erc20 balances.
Setup: Fauceted 1 USDC.
Before
```
Prompt: print USDC balance (token address: 0x036CbD53842c5426634e7929541eC2318f3dCF7e)
Balance of 0x036CbD53842c5426634e7929541eC2318f3dCF7e is 1000000
The USDC balance for the token address `0x036CbD53842c5426634e7929541eC2318f3dCF7e` is 1,000,000.
```
After
```
Prompt: print USDC balance (address is 0x036CbD53842c5426634e7929541eC2318f3dCF7e)
Balance of 0x036CbD53842c5426634e7929541eC2318f3dCF7e is 1
The USDC balance for the address 0x036CbD53842c5426634e7929541eC2318f3dCF7e is 1 USDC.
```
> fix: format erc20 balance

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/README.md
- python/coinbase-agentkit/changelog.d/+9b80489d.feature.md
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
enabling users to specify the rpc_url for the eth account wallet provider
*with invalid user defined rpc_url*:
```
wallet_provider = EthAccountWalletProvider(
config=EthAccountWalletProviderConfig(
account=account,
chain_id="84532",
rpc_url="https://base-sepolia.g.alchemy.com",
)
)
```
```
Prompt: native balance
Error getting balance: 404 Client Error: Not Found for url: https://base-sepolia.g.alchemy.com
It seems there was an error retrieving the native balance. Please try again later.
```
*with valid user define rpc_url*:
```
wallet_provider = EthAccountWalletProvider(
config=EthAccountWalletProviderConfig(
account=account,
chain_id="84532",
rpc_url="https://sepolia.base.org",
)
)
```
```
Prompt: native balance …
```
> feat(py): configurable eth account wallet provider rpc_url

- python/create-onchain-agent/changelog.d/+0fcb14d9.bugfix.md
- python/create-onchain-agent/templates/chatbot/.gitignore
When you run `pipx run create-onchain-agent`, the python project it would generate lacked a `.gitignore`.
Users should not need to create their own .gitignore.
Tested manually in two ways.
1. Generated using the public cli command, copy-pasted this .gitignore into it, and install/ran it
2. Use the local cli to generate, confirmed .gitignore appears in the generated project, and install/ran it
> fix: added .gitignore to chatbot template for cli

- python/create-onchain-agent/changelog.d/+cdfc1615.feature.md
- python/create-onchain-agent/templates/chatbot/.env.local.jinja
- python/create-onchain-agent/templates/chatbot/chatbot.py.jinja
- typescript/.changeset/dry-doors-rest.md
- typescript/create-onchain-agent/templates/next/app/api/agent/evm/privy/route.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/evm/viem/route.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/svm/privy/route.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/svm/solanaKeypair/route.ts
The CLI tools only included wallet persistence for the CDP wallet provider case in Typescript and Python.
However, we want the best devx experience.
* If a user runs it without a wallet, one should be created and saved
* If the app is re-run, that saved wallet data should be persisted.
Manually tested by generating every scenario via CLI, and testing them one by one.
> fix: cli wallet persistance

- typescript/.changeset/small-cloths-swim.md
- typescript/create-onchain-agent/src/cli.ts
- typescript/create-onchain-agent/src/constants.ts
- typescript/create-onchain-agent/src/fileSystem.ts
- typescript/create-onchain-agent/src/types.ts
- typescript/create-onchain-agent/src/utils.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/custom-evm/viem/route.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/evm/viem/route.ts
1.
The old selection put ALL networks (EVM & SVM, mainnets & testnets, even custom chain id) into one big select list.
This PR organizes this select into multiple smaller selections.
2. This fixes the "Custom Chain ID". Previously, a chain_id could be assigned, but no custom rpc was gathered, and you could still choose Privy (which does not expose a convenient way to customize by chainId/rpcUrl).
Now, going into the "Custom Chain ID" takes you through a different route entirely. You have to provide an accompanying rpc url, and a new api route is copied. This new API route is `custom-evm/viem`, which mirrors `evm/viem`, except rather than assigning a preconfigured Viem chain, it creates a new chain and assigns the chainId/rpc.
This new route already has the fixes from #468 and #484 built …
> feat: improved network selection in typescript/create-onchain-agent

- .github/workflows/publish_npm_agentkit_langchain.yml
`@coinbase/agentkit-langchain` depends on the local `@coinbase/agenkit` in order to be built correctly. This was changed and broken in: https://github.com/coinbase/agentkit/pull/466/files#diff-1aea946a0503fc7de81458f127e5aca1a224400432f9681d179f76db0902f607
> chore: fix publish agentkit langchain

- python/coinbase-agentkit/changelog.d/496.bugfix.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/compound/compound_action_provider.py
Removes a call to `get_network()` which is not needed for the `get_base_token_address` call.
Resolves: #496 
```
Prompt: Borrow 0.01 USDC from compound
Borrowed 0.01 USDC from Compound. Transaction hash: 0x12d060fd4748ce6d5dfd8bcb6f4f9e57c761b449af18992fd7f1409ec6ddc62a Health ratio changed from Infinity to 21.56
You have successfully borrowed 0.01 USDC from Compound. The transaction hash is: 0x12d060fd4748ce6d5dfd8bcb6f4f9e57c761b449af18992fd7f1409ec6ddc62a.
Your health ratio is now at 21.56. If you need further assistance, feel free to ask!
```
> fix: Compound borrow action

- typescript/.changeset/ripe-buttons-dress.md
- typescript/create-onchain-agent/templates/next/app/page.tsx
A inconsistent linter error can occur on the Next project generated.
Upon further inspection, the error can be ignored by passing along the full props.
My colleague who ran into the error tested this fix manually
> fix: linter error in ts cli's generated project

- typescript/.changeset/chubby-hornets-end.md
- typescript/create-onchain-agent/src/cli.ts
- typescript/create-onchain-agent/src/constants.ts
- typescript/create-onchain-agent/src/types.ts
- typescript/create-onchain-agent/templates/next/.gitignore
- typescript/create-onchain-agent/templates/next/app/api/agent/evm/smart/route.ts
- typescript/create-onchain-agent/templates/next/package.json
With the release of `@coinbase/agentkit` 0.2.3,`SmartWalletProvider` have been added.
This PR adds support to `npm create onchain-agent` to create a API endpoint that uses the SmartWalletProvider when selected.
When using the CLI for a EVM mainnet/testnet, `SmartWallet` is an option:
The .env.local generated will require CDP keys + OpenAI key, and optionally require a private key/network id
Putting the required env vars into .env (CDP keys + OpenAI Keys) is sufficient to get the bot running. The optional values are unnecessary to run, even private key
Killing the process and restarting it will load the private key/smart wallet address from the saved file, reconstituting state:
When using the CLI, picking a custom chain ID does NOT prompt for SmartWallet and instead defaults to Viem:
When …
> feat: added smart wallet support to npm create onchain-agent

- typescript/.changeset/breezy-parks-buy.md
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
- typescript/agentkit/src/action-providers/erc721/constants.ts
- typescript/agentkit/src/action-providers/erc721/erc721ActionProvider.test.ts
- typescript/agentkit/src/action-providers/erc721/erc721ActionProvider.ts
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/opensea/README.md
- typescript/agentkit/src/action-providers/opensea/index.ts
- typescript/agentkit/src/action-providers/opensea/openseaActionProvider.test.ts
- typescript/agentkit/src/action-providers/opensea/openseaActionProvider.ts
- typescript/agentkit/src/action-providers/opensea/schemas.ts
- typescript/agentkit/src/action-providers/opensea/utils.ts
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
- typescript/examples/langchain-cdp-chatbot/chatbot.ts
- typescript/package-lock.json
Adds new OpenseaActionProvider to handle interactions with opensea.
So far only one action is implemented (list_nft) that creates a listing on opensea.
Additional actions like accept/create offer may be added in the future.
This implementation uses the opensea-js sdk that is added as new dependency and requires an opensea api key (https://docs.opensea.io/reference/api-overview). The new action is added in the chatbot.ts example, only if an OPENSEA_API_KEY is set.
The OpenSea SDK requires an ethers signer which is created when initialising OpenseaActionProvider with the privateKey to the account holding the NFT. In the chatbot.ts example, I extract the privateKey from the CdpWalletProvider. This is a bit of a hack but I couldn't find a way to directly use a EvmWalletProvider to create a …
> feat: add action to list nfts on opensea (ts)

- typescript/agentkit/README.md
After merging #261 I realized there was missing documentation of this new provider in the `typescript/agentkit` README
> chore: added opensea action provider to README

- typescript/create-onchain-agent/templates/next/app/api/agent/evm/privy/route.ts
I corrected a typo in the variable name used for wallet data configuration. It was previously written as `PrviyWalletData`, which is clearly a mistake. The correct name should be `PrivyWalletData`.
> chore: fix typo in wallet data configuration variable name

- typescript/.changeset/all-nails-cry.md
- typescript/.changeset/config.json
- typescript/framework-extensions/vercel-ai-sdk/package.json
- typescript/framework-extensions/vercel-ai-sdk/tsconfig.json
- typescript/package-lock.json
This PR introduces changes to the `@coinbase/agentkit-vercel-ai-sdk` packaging setup to bring it more in line with a true "extension" or "plugin" style package. This means that it no longer directly depends on `@coinbase/agentkit` or Vercel's `ai` package, freeing up consumers to manage the versions of these packages themselves.
Along with the changes to the `changesets` config, this has the added benefit of not having to bump `@coinbase/agentkit-vercel-ai-sdk` whenever changes are added to `@coinbase/agentkit`.
This was tested locally by packaging up `@coinbase/agentkit` and `@coinbase/agentkit-vercel-ai-sdk`, and installing them locally in a standalone project, which can be seen here: https://github.com/0xRAG/peer-playground
Steps taken:
1. In `typescript/`, run `npm i && npm run build` …
> chore(vercel-ai-sdk): improve dependency management

- .github/labeler.yml
This label gets re-added on every push to a PR. I think this label can be implied by whether or not a maintainer has given an initial acknowledgement on an open PR.
> chore: remove noisy label

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/changelog.d/+14ef2776.feature.md
- python/coinbase-agentkit/poetry.lock
- python/coinbase-agentkit/pyproject.toml
Edwards key support was added to `cdp-sdk` 0.20.0. We are updating from `0.19.0` to `0.21.0` to inherit this feature.
```
Starting Agent...
Available modes:
1. chat    - Interactive chat mode
2. auto    - Autonomous action mode
Choose a mode (enter number or name): 1
Starting chat mode... Type 'exit' to end.
Prompt: What is your wallet and address?
- Address: 0x33503a7E9243f837b85F6E8CAb1ee914B1BddE0c
- Network:
- Native Balance: 0
My wallet address is **0x33503a7E9243f837b85F6E8CAb1ee914B1BddE0c** on the **base-sepolia** network.
```
> chore: python bump cdp sdk version

- typescript/create-onchain-agent/src/constants.ts
- typescript/create-onchain-agent/src/types.ts
- typescript/create-onchain-agent/src/utils.ts
This PR removes some handwritten types in favor of const assertion + indexed access to allow TypeScript to infer the types from the constants.
The package still builds, and the resulting types are exactly the same as before:
> chore: infer types from constants

- typescript/create-onchain-agent/templates/mcp/.gitignore
- typescript/create-onchain-agent/templates/mcp/README.md
- typescript/create-onchain-agent/templates/mcp/package.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/custom-emv/viem/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/custom-emv/viem/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/cdp/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/cdp/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/privy/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/privy/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/smart/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/smart/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/viem/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/viem/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/svm/privy/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/svm/privy/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/svm/solana-keypair/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/svm/solana-keypair/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/index.ts
- typescript/create-onchain-agent/templates/mcp/tsconfig.json
- typescript/package-lock.json
- typescript/package.json
Adds MCP template files which will be used in https://github.com/coinbase/agentkit/pull/569 to allow users to generate MCP projects.
Shown in https://github.com/coinbase/agentkit/pull/569
> chore: add mcp template

- python/create-onchain-agent/templates/beginner/.env.local.jinja
With the beginner template, I made the mistake of removing .jinja from the file extension, because templating the .env file was not required for this template. However, `.env.local` being the newly named file got ignored, as pushing up .env files is unsafe.
This PR reintroduced the env file
> fix: readded missing .env.local file

- .github/workflows/publish_nightly.yml
Nightlies are failing because the action tries to publish built artifacts (e.g. `create-onchain-agent/templates/next`). This PR updates the action to ignore `dist`, and the `create-onchain-agent` templates.
Also ignores the GitHub Release creator until we fix some issues there:
* Links to some packages are incorrect
* Unreleased changelog needs to accumulate from the changesets / changelog.d directory
> chore: fix nightly

- typescript/.changeset/breezy-badgers-marry.md
- typescript/.changeset/config.json
- typescript/create-onchain-agent/README.md
- typescript/create-onchain-agent/src/cli.ts
- typescript/create-onchain-agent/src/constants.ts
- typescript/create-onchain-agent/src/types.ts
- typescript/create-onchain-agent/src/utils.ts
Adds option to generate MCP Server project.
Testing was done locally by:
For each network family & wallet provider permutation:
1. Building`create-onchain-agent`
2. Going into the `dist` folder and running `node esm/cli.js`
3. Selecting options to generate a project
4. Executing steps to build / run the generated project
5. Opening Claude Desktop and asking it to print wallet details, then verifying the details are correct given the network family & wallet provider permutation
| EVM + CDP Prompt |
| - |
| <img width="1326" alt="image" src="https://github.com/user-attachments/assets/00ab5957-e878-43d6-9a47-dae57c893c88" /> |
| EVM + CDP Claude |
| - |
| <img width="1112" alt="image" src="https://github.com/user-attachments/assets/0268bad2-b88c-4a07-b40b-11f7c1e6a142" /> |
| EVM + …
> feat(create-onchain-agent): add mcp to typescript cli

- python/coinbase-agentkit/changelog.d/573.bugfix.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/morpho_action_provider.py
- python/coinbase-agentkit/tests/action_providers/morpho/test_morpho_action_provider.py
- typescript/.changeset/chubby-squids-cover.md
- typescript/agentkit/src/action-providers/morpho/morphoActionProvider.test.ts
- typescript/agentkit/src/action-providers/morpho/morphoActionProvider.ts
- Bug forced morpho deposit asset units to have 18 decimals (WETH)
- Change updates decimal parsing to use proper units for the given ERC20 token to deposit
- Unit tests
> fix: Morpho Deposit Atomic Unit Conversion

- python/create-onchain-agent/templates/beginner/README.md.jinja
- python/create-onchain-agent/templates/chatbot/README.md.jinja
- python/examples/openai-agents-sdk-cdp-chatbot/README.md
chore: added readme tip to surpress warning
> chore: added readme tip to surpress warning

- typescript/.changeset/breezy-badgers-marry.md
- typescript/.changeset/chubby-squids-cover.md
- typescript/.changeset/config.json
- typescript/.changeset/famous-pugs-divide.md
- typescript/.changeset/slick-points-smile.md
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
- typescript/create-onchain-agent/CHANGELOG.md
- typescript/create-onchain-agent/package.json
- typescript/create-onchain-agent/templates/mcp/package.json
- typescript/create-onchain-agent/templates/next/package.json
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-smart-wallet-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
- typescript/examples/vercel-ai-sdk-cdp-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
- typescript/framework-extensions/model-context-protocol/package.json
- typescript/framework-extensions/vercel-ai-sdk/package.json
- typescript/package-lock.json
> chore: version typescript packages

- typescript/.changeset/ninety-gifts-know.md
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/messari/README.md
- typescript/agentkit/src/action-providers/messari/index.ts
- typescript/agentkit/src/action-providers/messari/messariActionProvider.test.ts
- typescript/agentkit/src/action-providers/messari/messariActionProvider.ts
- typescript/agentkit/src/action-providers/messari/schemas.ts
- typescript/examples/langchain-cdp-chatbot/chatbot.ts
This PR adds a new Messari action provider that enables AI agents to query the Messari AI toolkit for crypto market research data. The provider allows agents to ask research questions about market data, statistics, rankings, historical trends, and information about specific protocols, tokens, or platforms.
The implementation follows the AgentKit action provider pattern and includes comprehensive tests.
Chatbot:  typescript/examples/langchain-cdp-chatbot/chatbot.ts
Network: Sepolia
Setup: Added the Messari action provider + add MESSARI_API_KEY to .env
```
Prompt: what is the current TVL of Aave on Base
Messari Research Results:
The current Total Value Locked (TVL) of Aave on the Base network is approximately $2,684,741,069.77.
The current Total Value …
```
> Messari action provider

- python/coinbase-agentkit/changelog.d/514.bugfix.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc20/erc20_action_provider.py
This PR fixes the ERC20 transfer checksum validation issues that were causing Web3.py validation errors during token transfers. The fix ensures both contract and destination addresses are properly converted to EIP-55 checksum format before being used in transactions.
Key changes:
- Added proper EIP-55 checksum conversion for both contract and destination addresses
- Improved code efficiency by reusing Web3 instance
- Fixed error messages related to invalid checksum addresses
Closes #514
```
Chatbot: python/examples/langchain-cdp-chatbot/chatbot.py
Network: Base Sepolia
Setup: Wallet with USDC tokens for testing transfers
Prompt: Transfer 1 USDC to 0xb4fbf271143f4fbf7b91c5ded31805e1b2b0bc1d
Transferred 1 of 0xB4FBF271143F4FBf7B91C5ded31805e1B2B0bC1D to …
```
> fix: ERC20 Transfer Checksum Validation (#514)

- typescript/.changeset/ninety-gifts-know.md
- typescript/agentkit/README.md
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/messari/README.md
- typescript/agentkit/src/action-providers/messari/constants.ts
- typescript/agentkit/src/action-providers/messari/index.ts
- typescript/agentkit/src/action-providers/messari/messariActionProvider.test.ts
- typescript/agentkit/src/action-providers/messari/messariActionProvider.ts
- typescript/agentkit/src/action-providers/messari/schemas.ts
- typescript/agentkit/src/action-providers/messari/types.ts
- typescript/agentkit/src/action-providers/messari/utils.ts
added messari action provider
* research_question
[x] chatbot
[x] unit
*What is the current price of Ethereum?*
```
As of March 26, 2025, the current price of Ethereum (ETH) is **$2,012.99**. Here are some additional metrics:
- **24-hour Price Change**: 
- Absolute Value: -$55.31 
- Percentage: -2.67%
- **Current Market Capitalization**: $242,471,578,768
- **24-hour Trading Volume**: $7,011,385,937.27
- **Circulating Supply**: 120,639,295.2 ETH
If you need more information or assistance, feel free to ask!
```
*Tell me about the recent news regarding the Hyperliquid token vault HLP that caused some commotion?*
```
The recent news surrounding Hyperliquid's HLP (Hyperliquidity Provider) vault highlights a significant incident that stirred commotion in the community:
1. **Exploit Incident**: …
```
> feat(ts): messari action provider

- python/coinbase-agentkit/README.md
I noticed `python/coinbase-agentkit/README.md` was missing a entry for the new Nillion Action Provider
> fix: added Nillion to python's core readme

- typescript/.changeset/sad-windows-divide.md
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/smart/getAgentKit.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/smart/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/prepareAgentkit/agentkit/evm/smart/prepareAgentkit.ts
- typescript/examples/langchain-smart-wallet-chatbot/chatbot.ts
There is a bug where smart wallet code generated from the npm cli would include `CdpWalletActionProvider` included in the list of action providers. These actions cannot be used by any wallet provider other than the `CdpWalletProvider`.
> fix: removed CdpWalletActionProvider from smart wallet action provider lists

- typescript/.changeset/cold-cougars-hug.md
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
When an agent uses multiple actions that send transactions at once, the cdp wallet provider might send them all at once with the same nonce. This PR implements a transaction queue so the wallet provider will await previous transactions before sending a new one to avoid nonce collisions.
Example:
Chatbot: langchain-cdp-chatbot
Network: base
Setup: relevant assets topped up
Prompt: "supply 5 usdc and 0.001 weth into compound"
Response: 
```
You have successfully supplied **5 USDC** to Compound:
- **Transaction Hash:** [0x6d451e11557fdd1ae207ec8d418a4a7d13214fa614b7ae35104b503cdae0813c](https://etherscan.io/tx/0x6d451e11557fdd1ae207ec8d418a4a7d13214fa614b7ae35104b503cdae0813c)
However, there was an error when trying to supply **0.001 WETH** due to a "Replacement transaction underpriced" …
```
> Add transaction queue to cdp wallet provider

- typescript/.changeset/config.json
fix: changesets bump versions with workspace protocol only
> fix: changesets bump versions with workspace protocol only

- typescript/.changeset/giant-impalas-relate.md
- typescript/agentkit/package.json
- typescript/agentkit/src/wallet-providers/privyEvmDelegatedEmbeddedWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/privyEvmDelegatedEmbeddedWalletProvider.ts
- typescript/agentkit/src/wallet-providers/privyShared.ts
- typescript/agentkit/src/wallet-providers/privySvmWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/privySvmWalletProvider.ts
- typescript/agentkit/src/wallet-providers/privyWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/privyWalletProvider.ts
- typescript/pnpm-lock.yaml
The `@privy-io/server-auth` package has a dev dependency on `@privy-io/public-api` that needs to be explicit.
The version of `@privy-io/public-api` chosen was selected by looking up the `package.json` from our `@privy-io/server-auth` version and adding the same version in our codebase.
https://www.npmjs.com/package/@privy-io/server-auth/v/1.18.4?activeTab=code
After adding this install, my environment unveiled a problem that my cjs/esm r&d venture also showcased - `createPrivyClient` cannot have a undefined `chainType`. At runtime we were ensuring this was never the case, but at build time, our types are incompatible with that.
To fix this properly, 
1. I adjusted the base `PrivyWalletConfig` and removed the `chainType` completely
2. I moved it to a `&` on the `createPrivyWallet`'s config …
> Fixed privy dependency bug

- .github/workflows/publish_pypi_coinbase_agentkit.yml
- .github/workflows/publish_pypi_coinbase_agentkit_langchain.yml
- .github/workflows/publish_pypi_coinbase_agentkit_openai_agents_sdk.yml
- .github/workflows/publish_pypi_create_onchain_agent.yml
After #657, tagging is a manual step of phase 3, instead of something we rely on Github Actions for. 
The "Why" is I decided to make it a developer-managed step rather than over-rely on workflows. This decision is in an effort to make releases less brittle (hard to test workflows, especially with the new branch protection rules), more testable (can be partially tested when written as code run on a developers machine) and easier to review (as code, we have more control, such as letting developers run drafts before jumping straight into pushing up tags).
The "Why now?" is because we removed `tag.sh` in favor of having the Github Actions tag in the release workflow, however a [bug was uncovered](https://github.com/coinbase/agentkit/actions/runs/14273038306/job/40010380759) because the bot …
> chore: removed tagging from gha in python

- .github/workflows/format.yml
- .github/workflows/lint.yml
- .github/workflows/publish_docs.yml
- .github/workflows/unit_tests.yml
Hey ! GitHub‑hosted runners now use Node 20, so checkout v4 is required
This PR updates all workflows to actions/checkout@v4 , no functional changes expected
> ci: bump actions/checkout to v4

- typescript/agentkit/src/action-providers/cdp-v2/cdpApiV2ActionProvider.ts
- typescript/agentkit/src/wallet-providers/cdpV2EvmWalletProvider.ts
- typescript/agentkit/src/wallet-providers/cdpV2Shared.ts
Assigning gas estimations and chain id in sendTransaction to ensure they are EIP1559 transactions.
Tested locally via confirming the issue existed leveraging the wrap eth to weth action, and then ensuring it worked locally after the above changes.
Note: I noticed the `CdpV2ApiActionProvider` was finicky about injecting the wallet provider. This is because my custom type was failing the `=== WalletProvider` check in certain environments (worked with vercel ai agents, but was finicky in langchain). I refactor to a type guard.
> fix: assigning gas estimations and chainId in sendTransaction

- python/coinbase-agentkit/changelog.d/+fcba5356.bugfix.md
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_evm_smart_wallet_provider.py
- python/coinbase-agentkit/tests/wallet_providers/cdp_evm_smart_wallet_provider/conftest.py
- python/coinbase-agentkit/tests/wallet_providers/cdp_evm_smart_wallet_provider/test_basic_methods.py
- python/create-onchain-agent/templates/chatbot/setup.py.jinja
- python/examples/langchain-cdp-smart-wallet-chatbot/chatbot.py
- python/examples/openai-agents-sdk-smart-wallet-chatbot/chatbot.py
- python/scripts/sync_examples.sh
1. If the owner was a server wallet, we were running into issues where the socket would close
2. If there was any mismatch between the file and .env vars, the wrong owner might get loaded for a smart wallet, which would fail
This PR addresses those changes
> fix: CdpEvmSmartWalletProvider

- CONTRIBUTING-TYPESCRIPT.md
The broken link in CONTRIBUTING-TYPESCRIPT.md has been updated to point to the correct file path:
typescript/framework-extensions/langchain/src/index.ts.
> docs: fix 404 link

- typescript/.changeset/cyan-llamas-bow.md
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/cdp/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/privy/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/smart/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/svm/privy/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/framework/langchain/create-agent.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/framework/langchain/route.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/framework/vercel-ai-sdk/create-agent.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/framework/vercel-ai-sdk/route.ts
We received a report from TBA about improving our error handling in the Next generated chatbot. We wholeheartedly agree, and this seeks to improve it.
Now, when the UI runs into an issue, the error messages propagated come from checks in anticipation of these issues, and are readable non-vague instructions on overcoming the error.
> feat: improved error handling in next template of cli

- python/framework-extensions/langchain/README.md
Updated the reference URL for the chatbot example to point to the correct location. The previous link was pointing to a non-existent path causing a 404 error. This change ensures users can access the proper example when learning how to implement AgentKit with LangChain.
> docs: Update agentkit link README.md

- typescript/.changeset/config.json
- typescript/.changeset/dirty-candies-thank.md
We are temporarily ignoring the templates under the create-onchain-agent CLI, until after this release. However, the way we ignored it broke changeset validation's ignore: https://github.com/coinbase/agentkit/actions/runs/15324606781/job/43115854116
This PR temporarily fixes it so that the automated flow can proceed
> fix: ignore templates

- python/create-onchain-agent/CHANGELOG.md
- python/create-onchain-agent/changelog.d/+4cc563fc.feature.md
- python/create-onchain-agent/pyproject.toml
- python/create-onchain-agent/templates/beginner/pyproject.toml.jinja
- python/create-onchain-agent/templates/chatbot/pyproject.toml.jinja
- python/create-onchain-agent/uv.lock
- python/examples/langchain-cdp-chatbot-with-aws-bedrock/uv.lock
- python/examples/langchain-cdp-server-chatbot/uv.lock
- python/examples/langchain-cdp-smart-wallet-chatbot/uv.lock
- python/examples/langchain-eth-account-chatbot/uv.lock
- python/examples/langchain-nillion-secretvault-chatbot/uv.lock
- python/examples/langchain-twitter-chatbot/uv.lock
- python/examples/openai-agents-sdk-cdp-chatbot/uv.lock
- python/examples/openai-agents-sdk-cdp-voice-chatbot/uv.lock
- python/examples/openai-agents-sdk-smart-wallet-chatbot/uv.lock
- python/framework-extensions/langchain/CHANGELOG.md
- python/framework-extensions/langchain/docs/conf.py
- python/framework-extensions/langchain/pyproject.toml
- python/framework-extensions/langchain/uv.lock
- python/framework-extensions/openai-agents-sdk/CHANGELOG.md
- python/framework-extensions/openai-agents-sdk/pyproject.toml
- python/framework-extensions/openai-agents-sdk/uv.lock
Now that `coinbase-agentkit` version `0.6.0` is released, we can deploy the dependent packages.
`coinbase-agentkit-langchain` was bumped to `0.5.0`
`coinbase-agentkit-openai-agents-sdk` was bumped to `0.5.0`
`create-onchain-agent` was bumped to `0.7.0`
> chore: bump python packages

- typescript/agentkit/README.md
Replaced the outdated and broken link to the Solana web3.js documentation (https://solana-labs.github.io/solana-web3.js/) with the official and up-to-date Solana JavaScript SDK documentation (https://solana.com/docs/clients/javascript) in the README. This ensures users have access to the latest resources and usage examples for Solana web3.js.
> Fix broken Solana web3.js documentation link in README

- typescript/agentkit/README.md
Changed `AgentKit.from` argument keys from cdpApiKeyPrivate -> cdpApiKeySecret
> Update README.md to correct `AgentKit.from` argument keys from cdpApiKeyPrivate -> cdpApiKeySecret

- typescript/create-onchain-agent/CHANGELOG.md
**Description:**  
This pull request corrects a typo in the CHANGELOG file, changing "persistance" to the correct spelling "persistence" in the entry for wallet persistence in all templates. No other changes were made.
> Fix typo: "persistance" → "persistence" in CHANGELOG

- typescript/agentkit/src/action-providers/across/README.md
Corrected a minor typo in the warning section of the README (briding → bridging) to improve clarity and maintain professional documentation standards.
> Fix typo in bridging warning message

- CONTRIBUTING-TYPESCRIPT.md
Hey devs, fixed reference in CONTRIBUTING-TYPESCRIPT.md
https://github.com/elizaOS/eliza/blob/develop/packages/plugin-agentkit/src/actions.ts#L31 - fix dead reference
https://github.com/elizaos-plugins/plugin-agentkit/blob/main/src/actions.ts#L25 - new link
> fix elizaos-plugins reference

- typescript/.changeset/nice-ducks-search.md
- typescript/agentkit/README.md
- typescript/agentkit/src/action-providers/farcaster/README.md
- typescript/agentkit/src/action-providers/farcaster/farcasterActionProvider.test.ts
- typescript/agentkit/src/action-providers/farcaster/farcasterActionProvider.ts
- typescript/agentkit/src/action-providers/farcaster/schemas.ts
- typescript/agentkit/src/action-providers/twitter/README.md
- typescript/agentkit/src/action-providers/twitter/schemas.ts
- typescript/agentkit/src/action-providers/twitter/twitterActionProvider.test.ts
- typescript/agentkit/src/action-providers/twitter/twitterActionProvider.ts
Added media upload support for Twitter and embeds support for Farcaster
- FarcasterActionProvider: post_cast actions takes new optional embeds URL as input
- TwitterActionProvider: 
- new action to upload upload_media returns media_id
- post_tweet/post_tweet_reply take new optional media_ids as input
```
Chatbot: typescript/examples/langchain-cdp-chatbot/chatbot.ts
Network: Base Sepolia
```
```
Prompt: farcaster post with text "Testing in prod" and embeds: "https://true-cast.vercel.app", "https://true-cast.vercel.app/trueCast.png"
Successfully posted cast to Farcaster:
{"success":true,"cast":{"hash":"0x4f24e69ed1f51aaeb65e79b9968bd72742bd4899","author":{"object":"user","fid":1046472,"username":"truecastagent","display_name":"TrueCast","pfp_url":"https://imagedelivery.ne …
```
> feat:post embeds on Farcaster and media on Twitter (ts)

- python/README.md
- python/examples/strands-agents-cdp-server-chatbot/.env.local
- python/examples/strands-agents-cdp-server-chatbot/Makefile
- python/examples/strands-agents-cdp-server-chatbot/README.md
- python/examples/strands-agents-cdp-server-chatbot/chatbot.py
- python/examples/strands-agents-cdp-server-chatbot/pyproject.toml
- python/examples/strands-agents-cdp-server-chatbot/uv.lock
- python/examples/strands-agents-cdp-server-chatbot/wallet_data_base_sepolia.txt
- python/framework-extensions/strands-agents/CHANGELOG.md
- python/framework-extensions/strands-agents/Makefile
- python/framework-extensions/strands-agents/README.md
- python/framework-extensions/strands-agents/coinbase_agentkit_strands_agents/__init__.py
- python/framework-extensions/strands-agents/coinbase_agentkit_strands_agents/strands_agents_tools.py
- python/framework-extensions/strands-agents/docs/Makefile
- python/framework-extensions/strands-agents/docs/coinbase_agentkit_strands_agents.rst
- python/framework-extensions/strands-agents/docs/conf.py
- python/framework-extensions/strands-agents/docs/index.rst
- python/framework-extensions/strands-agents/docs/make.bat
- python/framework-extensions/strands-agents/docs/modules.rst
- python/framework-extensions/strands-agents/pyproject.toml
- python/framework-extensions/strands-agents/uv.lock
---
**Changes:**
- Added `coinbase-agentkit-strands-agents` package in `python/framework-extensions/strands-agents/`
- Provides `get_strands_tools()` function to convert AgentKit actions into Strands-Agents-compatible tools
- Added example chatbot demonstrating the integration in `python/examples/strands-agents-cdp-server-chatbot/`
- Includes automatic type hint inference from AgentKit action schemas
- Follows established patterns from other framework extensions (langchain, openai-agents-sdk)
This enables developers using Strands Agents to leverage all existing AgentKit CDP actions (wallet operations, token transfers, trading, etc.) with minimal setup.
---
```
Chatbot: python/examples/strands-agents-cdp-server-chatbot/chatbot.py
Network: Base Sepolia
Setup: Configured with CDP API …
```
> Strands Agents framework Extension

- typescript/.changeset/poor-phones-hide.md
- typescript/agentkit/README.md
- typescript/agentkit/package.json
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/zora/README.md
- typescript/agentkit/src/action-providers/zora/index.ts
- typescript/agentkit/src/action-providers/zora/schemas.ts
- typescript/agentkit/src/action-providers/zora/utils.ts
- typescript/agentkit/src/action-providers/zora/zoraActionProvider.test.ts
- typescript/agentkit/src/action-providers/zora/zoraActionProvider.ts
- typescript/pnpm-lock.yaml
Implements Zora Coins SDK integration
- Adds ZoraActionProvider
- Adds coinIt action to create a coin on Zora with given name, symbol, description and image
- Image can be local file which is then uploaded to ipfs or https url
- Requires Pinata API key to upload metadata 
```
Chatbot: typescript/examples/langchain-cdp-chatbot/chatbot.ts
Network: Base mainnet
Prompt: create new zora coin with name TestInProd, symbol TP, image https://metadata-storage-ftm.s3.us-east-2.amazonaws.com/ai-image-485-1746453858028.png description Testin in prod
{"success":true,"transactionHash":"0xd13835e50fdfe2aca5b2b4c981dc67cfd0ba6e90ea0724810673e34b3cce06d9","coinAddress":"0x0C66a731f293d7bD024Dc6D0b99c403019Cc3972","imageUri":"https://metadata-storage-ftm.s3.us-east-2.amazonaws.com/ai-imag …
```
>  Zora Coins SDK 

- typescript/.changeset/fresh-memes-move.md
- typescript/agentkit/README.md
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/truemarkets/README.md
- typescript/agentkit/src/action-providers/truemarkets/constants.ts
- typescript/agentkit/src/action-providers/truemarkets/index.ts
- typescript/agentkit/src/action-providers/truemarkets/schemas.ts
- typescript/agentkit/src/action-providers/truemarkets/truemarketsActionProvider.test.ts
- typescript/agentkit/src/action-providers/truemarkets/truemarketsActionProvider.ts
- typescript/agentkit/src/action-providers/truemarkets/utils.ts
Adds **TrueMarketsActionProvider**  to interact with **Truemarkets** prediction markets on Base.
The following actions are implemented:
- `get_active_markets`: Get active prediction markets from Truemarkets
- Returns a list of markets with their ID, contract address and market question
- Supports pagination and sorting options
- `get_market_details`: Get detailed information for a specific market
- Takes a market address as input
- Returns market information including:
- Market question, source, and status
- Pool addresses and liquidity
- YES/NO token prices
- Pool balances and TVL 
```
Chatbot: typescript/examples/langchain-cdp-chatbot/chatbot.ts
Network: Base Mainnet
Prompt: list 10 newest truemarkets prediction markets …
```
> feat:Truemarkets action provider (ts)

- typescript/.changeset/short-carpets-share.md
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/smart/prepare-agentkit.ts
create-onchain-agent next template (smart wallet) build fails with:
```
./app/api/agent/prepare-agentkit.ts:105:7
Type error: Object literal may only specify known properties, and 'smartWalletAddress' does not exist in type 'CdpSmartWalletProviderConfig'.
103 |       // eslint-disable-next-line @typescript-eslint/no-explicit-any
104 |       owner: owner as any,
105 |       smartWalletAddress: walletData?.smartWalletAddress,
106 |       paymasterUrl: undefined, // Sponsor transactions: https://docs.cdp.coinbase.com/paymaster/docs/welcome
107 |     });
108 |
```
This PR fixes the config following the implementation in the corresponding chatbot example: https://github.com/coinbase/agentkit/blob/main/typescript/examples/langchain-cdp-smart-wallet-chatbot/chatbot.ts
> fix: bug in configureWithWallet config

- python/examples/strands-agents-cdp-server-chatbot/uv.lock
- python/framework-extensions/strands-agents/pyproject.toml
- python/framework-extensions/strands-agents/uv.lock
Updated from using the local build to the published build now that allora-sdk dependency has been removed.
This is the final unblock to run publishing
> chore: update strands to use deployed agentkit v0.7.1

- typescript/.changeset/slimy-garlics-drum.md
- typescript/agentkit/README.md
- typescript/agentkit/package.json
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/superfluid/README.md
- typescript/agentkit/src/action-providers/superfluid/constants.ts
- typescript/agentkit/src/action-providers/superfluid/graphQueries/endpoints.ts
- typescript/agentkit/src/action-providers/superfluid/graphQueries/queries.ts
- typescript/agentkit/src/action-providers/superfluid/graphQueries/superfluidGraphQueries.ts
- typescript/agentkit/src/action-providers/superfluid/graphQueries/types.ts
- typescript/agentkit/src/action-providers/superfluid/index.ts
- typescript/agentkit/src/action-providers/superfluid/schemas.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidActionProvider.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidPoolActionProvider.test.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidPoolActionProvider.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidQueryActionProvider.test.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidQueryActionProvider.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidStreamActionProvider.test.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidStreamActionProvider.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidSuperTokenCreatorActionProvider.test.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidSuperTokenCreatorActionProvider.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidWrapperActionProvider.test.ts
- typescript/agentkit/src/action-providers/superfluid/superfluidWrapperActionProvider.ts
- typescript/agentkit/src/action-providers/superfluid/utils/parseLogs.ts
- typescript/pnpm-lock.yaml
[Link to Issue](https://github.com/coinbase/agentkit/issues/280)
Superfluid action providers, broken up by functionality (create stream, create pool, update stream, update pool). We experienced need for Superfluid functionality in our agent and decided to include the implementation in the core repo.
Very little qualified impact due to the self contained nature of the action. Only dependency is the graphql-request package, which can be omitted in the event of an error.
- Create pool
- Update member units
- Create stream
- Update stream
- Close stream
- Query open streams
- Creates a SuperToken (wrapper) implementation for an underlying ERC20
- Wraps an ERC20 into its Super Token implementation
```
Chatbot: langchain-cdp-chatbot
Network: Base Mainnet
Setup: Add relevant actions …
```
> feat: superfluid typescript action provider

- typescript/.changeset/whole-times-fetch.md
- typescript/agentkit/README.md
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/zeroX/README.md
- typescript/agentkit/src/action-providers/zeroX/index.ts
- typescript/agentkit/src/action-providers/zeroX/schemas.ts
- typescript/agentkit/src/action-providers/zeroX/utils.ts
- typescript/agentkit/src/action-providers/zeroX/zeroXActionProvider.test.ts
- typescript/agentkit/src/action-providers/zeroX/zeroXActionProvider.ts
Added 0x Protocol support for token swaps on EVM networks
New ZeroXActionProvider:
- get_swap_price_quote_from_0x: fetches price quote for token swaps
- execute_swap_on_0x: executes token swaps with automatic permit2 approvals if needed
- Supports native ETH and ERC20 tokens
- requires 0x API key: https://0x.org/docs/
```
Chatbot: typescript/examples/langchain-cdp-chatbot/chatbot.ts
Network: Base Mainnet
Prompt: get quote for swapping 0.001 ETH (0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee) to USDC (0x833589fcd6edb6e08f4c7c32d4f71b54bda02913) 
{"sellAmount":"0.001","sellToken":"0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee","buyAmount":"1.589364","minBuyAmount":"1.573522","buyToken":"0x833589fcd6edb6e08f4c7c32d4f71b54bda02913","totalNetworkFeeInETH":"0.000007152843753845","i …
```
> feat:trades via 0x

- typescript/.changeset/tasty-dragons-vanish.md
- typescript/agentkit/README.md
- typescript/agentkit/package.json
- typescript/agentkit/src/action-providers/clanker/README.md
- typescript/agentkit/src/action-providers/clanker/clankerActionProvider.test.ts
- typescript/agentkit/src/action-providers/clanker/clankerActionProvider.ts
- typescript/agentkit/src/action-providers/clanker/index.ts
- typescript/agentkit/src/action-providers/clanker/schemas.ts
- typescript/agentkit/src/action-providers/clanker/utils.ts
- typescript/agentkit/src/action-providers/clanker/utils/clankerBridge.ts
- typescript/agentkit/src/action-providers/index.ts
- typescript/pnpm-lock.yaml
This action adds Clanker token deployment support to the typescript implementation of AgentKit.
Although Clanker already has an agent that deploys tokens, their open library and protocol allows anyone to launch a "Clank" token and be recognized by their ecosystem.
```
Chatbot: langchain-cdp-chatbot
Network: Base Mainnet
Setup: Add ClankerActionProvider to the chatbot
```
```
Prompt: Can you clank a token with name [CDP Clanker], and symbol [CDPC] and image hosted at [https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF6hcTTU1A8Ymi2VldXqCsPkBu_ltAhIKiRg&s]?  vest 10%, locked for 30 days, and then vested for 30 days.  do this on base-mainnet
```
```
Response:
Internal address: 0xE8D165388b13c460F02f4dC922309450a9bF6f22
Clanker token deployed at …
```
> feat: added Clanker typescript action support

- python/coinbase-agentkit/changelog.d/579.bugfix.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/weth/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
Replaced a pydantic `@validator` by `@field_validator`, as `@validator` is deprecated and will be removed in future versions.
Other parts are already using `@field_validator`, this was the last usage of it.
Discovered it while integrating AgentKit into an AI Agent framework and writing tests, which where raising warnings:
```sh
venv/lib/python3.11/site-packages/coinbase_agentkit/action_providers/weth/schemas.py:15
/libertai-agents/libertai_agents/venv/lib/python3.11/site-packages/coinbase_agentkit/action_providers/weth/schemas.py:15: 
PydanticDeprecatedSince20: Pydantic V1 style `@validator` validators are deprecated. 
You should migrate to Pydantic V2 style `@field_validator` validators, see the migration guide for more details.
Deprecated in Pydantic V2.0 to be removed in V3.0. 
See …
```
> fix(py/weth): Replace deprecated pydantic @validator and class configs

- typescript/.changeset/stupid-goats-march.md
- typescript/agentkit/src/wallet-providers/viemWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/viemWalletProvider.ts
Allowed passing of a "hex" or bytes to "signMessage" for Viem & Viem-derived Wallet Providers
Currently Viem signing only supports strings. Viem itself can support Uint8Array & Hex ([code](https://github.com/wevm/viem/blob/main/src/actions/wallet/signMessage.ts#L82), [docs](https://viem.sh/experimental/erc7739/signMessage#message)).
As the `evmWalletProvider` doesn't support the `{ raw: <input> }`, we cast everything to a hex string based on the following logic and pass it into raw:
```
const hexMessage =
typeof message === "string" ? (isHex(message) ? message : toHex(message)) : message;
return this.#walletClient.signMessage({
account,
message: { raw: hexMessage },
});
```
This is to enable signing Hex messages as well as bytes (e.g. transaction hashes - this came up while trying to sign …
> feat: viem signing hex or uint8array

- typescript/.changeset/moody-places-burn.md
- typescript/agentkit/src/wallet-providers/cdpSmartWalletProvider.ts
Fixes issue in retrieving tx logs in CdpSmartWalletProvider, where occasionally transactionReceipt is not ready even though userOp was awaited
> fix: bug in retrieving tx logs for smart accounts
