coinbase/agentkit

- README.md
> fix: README Badges

- .github/workflows/publish_docs.yml
- GHA Docs Generation - Run commands inside poetry virtualenv
> fix: GHA Docs Generation - Run commands inside poetry virtualenv

- .github/workflows/publish_docs.yml
fix: GHA Docs - Use 1 root dir for docs site
> fix: GHA Docs - Use 1 root dir for docs site

- cdp-agentkit-core/cdp_agentkit_core/actions/deploy_nft.py
- cdp-agentkit-core/cdp_agentkit_core/actions/deploy_token.py
- cdp-agentkit-core/cdp_agentkit_core/actions/get_balance.py
- cdp-agentkit-core/cdp_agentkit_core/actions/mint_nft.py
- cdp-agentkit-core/cdp_agentkit_core/actions/request_faucet_funds.py
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/account_details.py
- cdp-agentkit-core/cdp_agentkit_core/actions/trade.py
- cdp-agentkit-core/cdp_agentkit_core/actions/transfer.py
- cdp-agentkit-core/tests/actions/test_deploy_nft.py
- cdp-agentkit-core/tests/actions/test_deploy_token.py
- cdp-agentkit-core/tests/actions/test_mint_nft.py
- cdp-agentkit-core/tests/actions/test_trade.py
- cdp-agentkit-core/tests/actions/test_transfer.py
- catch errors and return human readable strings for the LLM for all core actions
> chore: Catch errors in core actions

- cdp-agentkit-core/cdp_agentkit_core/actions/get_balance.py
- cdp-agentkit-core/cdp_agentkit_core/actions/mint_nft.py
- cdp-agentkit-core/cdp_agentkit_core/actions/register_basename.py
- cdp-agentkit-core/cdp_agentkit_core/actions/request_faucet_funds.py
- cdp-agentkit-core/cdp_agentkit_core/actions/trade.py
- cdp-agentkit-core/cdp_agentkit_core/actions/transfer.py
- cdp-langchain/examples/chatbot/chatbot.py
- Update prompts for v0 launch!
> chore: Improve Prompts V0

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/__init__.py
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/account_details.py
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/action.py
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/post_tweet.py
- twitter-langchain/README.md
- twitter-langchain/examples/account_details/account_details.py
- twitter-langchain/twitter_langchain/__init__.py
- twitter-langchain/twitter_langchain/twitter_api_wrapper.py
- twitter-langchain/twitter_langchain/twitter_tool.py
- twitter-langchain/twitter_langchain/twitter_toolkit.py
- Refactor `twitter-langchain` to align with the package/action structure of `cdp-langchain`
> feat: twitter langchain refinements

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/docs/conf.py
- cdp-agentkit-core/pyproject.toml
- twitter-langchain/CHANGELOG.md
- twitter-langchain/pyproject.toml
Release 0.0.5 cdp-agentkit-core
Release 0.0.5 twitter-langchain
> Release 0.0.5 Core|0.0.5 Twitter Langchain

- .github/workflows/publish_twitter_langchain.yml
> feat: gha to publish twitter-langchain to pypi

- .github/workflows/unit_tests.yml
> feat: twitter langchain gha unit tests

- .github/workflows/publish_docs.yml
- twitter-langchain/docs/Makefile
- twitter-langchain/docs/README.md
- twitter-langchain/docs/conf.py
- twitter-langchain/docs/index.rst
- twitter-langchain/docs/make.bat
- twitter-langchain/docs/modules.rst
- twitter-langchain/docs/twitter_langchain.rst
- twitter-langchain/poetry.lock
- twitter-langchain/pyproject.toml
- twitter-langchain/twitter_langchain/twitter_tool.py
- twitter-langchain/twitter_langchain/twitter_toolkit.py
> feat: twitter langchain docs gen and pub

- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/account_details.py
- cdp-agentkit-core/cdp_agentkit_core/actions/social/twitter/post_tweet_reply.py
- twitter-langchain/examples/chatbot/chatbot.py
- twitter-langchain/tests/actions/test_account_details.py
- twitter-langchain/tests/actions/test_account_mentions.py
- twitter-langchain/tests/actions/test_post_tweet.py
- twitter-langchain/tests/actions/test_post_tweet_reply.py
- twitter-langchain/tests/conftest.py
- twitter-langchain/tests/factories/twitter_factory.py
> feat: twitter langchain actions tests

- .github/workflows/publish_agentkit.yml
- .github/workflows/publish_langchain.yml
- .github/workflows/publish_twitter_langchain.yml
> feat: gha publish refinements

- .github/workflows/publish_agentkit.yml
- Fix agentkit core GHA publisher by updating `packages-dir`
> fix: GHA Release Agentkit Core

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/docs/conf.py
- cdp-agentkit-core/poetry.lock
- cdp-agentkit-core/pyproject.toml
- Release `cdp-agentkit-core` `0.0.7`
> chore: release cdp-agentkit-core 0.0.7

- cdp-langchain/CHANGELOG.md
- cdp-langchain/cdp_langchain/utils/cdp_agentkit_wrapper.py
- cdp-langchain/poetry.lock
- cdp-langchain/pyproject.toml
- cdp-langchain/tests/utils/test_cdp_agentkit_wrapper.py
* supporting wallet mnemonic phrase import
> feat: wallet mnemonic import

- cdp-agentkit-core/CHANGELOG.md
- cdp-agentkit-core/docs/conf.py
- cdp-agentkit-core/pyproject.toml
- Release `0.0.8` `cdp-agentkit-core` package with `wrap_eth` action
> chore: Release 0.0.8 cdp-agentkit-core

- README.md
- Format directory tree in README.md
> chore: Fix Dir tree in readme

- cdp-agentkit-core/python/CHANGELOG.md
- cdp-agentkit-core/python/cdp_agentkit_core/actions/__init__.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/morpho/constants.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/morpho/deposit.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/morpho/utils.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/morpho/withdraw.py
- cdp-agentkit-core/python/tests/actions/morpho/test_deposit.py
- cdp-agentkit-core/python/tests/actions/morpho/test_withdraw.py
- cdp-agentkit-core/python/tests/factories/asset_factory.py
- Add action `morpho_deposit` to deposit to Morpho Vault on Base
- Add action `morpho_withdraw` to withdraw from a Morpho Vault on Base
> feat(PSDK-854): Morpho Vault Deposit/Withdraw Actions

- README.md
README copy update from "on-chain" to "onchain"
> Update "on-chain" to "onchain"

- cdp-agentkit-core/python/README.md
- cdp-agentkit-core/python/pyproject.toml
- symlink core README so that `poetry publish` can find it
> chore: Fix Poetry Publish by Symlinking Core README

- cdp-agentkit-core/typescript/package.json
- cdp-langchain/typescript/CHANGELOG.md
- cdp-langchain/typescript/package.json
- package-lock.json
- Release cdp-langchain NPM 0.0.13
> chore: Release cdp-langchain NPM 0.0.13

- cdp-agentkit-core/typescript/package.json
- cdp-langchain/typescript/package.json
- package-lock.json
- twitter-langchain/typescript/CHANGELOG.md
- twitter-langchain/typescript/package.json
- Release `twitter-langchain` NPM `0.0.10`
- Fix `cdp-langchain` NPM `0.0.12` release
> chore: Release twitter-langchain NPM 0.0.10

- cdp-langchain/examples/chatbot-python/poetry.lock
- cdp-langchain/examples/chatbot-python/pyproject.toml
- cdp-langchain/examples/chatbot-typescript/package-lock.json
- cdp-langchain/examples/chatbot-typescript/package.json
- twitter-langchain/examples/chatbot-python/poetry.lock
- twitter-langchain/examples/chatbot-python/pyproject.toml
- twitter-langchain/examples/chatbot-typescript/package-lock.json
- twitter-langchain/examples/chatbot-typescript/package.json
- bump example chatbot deps
- For packages
-- `cdp-langchain` `0.0.11` PyPI
-- `twitter-langchain` `0.0.9` PyPI
-- `@coinbase/cdp-agentkit-core` `0.0.12`
-- `@coinbase/cdp-langchain` `0.0.13`
-- `@coinbase/twitter-langchain` `0.0.10`
> chore: Update Example Chatbot Deps

- cdp-langchain/examples/chatbot-python/poetry.lock
- cdp-langchain/examples/chatbot-python/pyproject.toml
- cdp-langchain/examples/chatbot-typescript/package.json
- package-lock.json
- twitter-langchain/examples/chatbot-python/poetry.lock
- twitter-langchain/examples/chatbot-python/pyproject.toml
- twitter-langchain/examples/chatbot-typescript/package-lock.json
- twitter-langchain/examples/chatbot-typescript/package.json
* bumped cdp-langchain example deps
* bumped twitter-langchain example deps
> core: bump example deps

- cdp-langchain/python/README.md
- cdp-langchain/typescript/README.md
* added morpho vault tooling to python & typescript readme's
> feat: readme updates for morpho vault tools

- cdp-agentkit-core/python/CHANGELOG.md
- cdp-agentkit-core/python/cdp_agentkit_core/actions/morpho/deposit.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/morpho/withdraw.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/create_flow.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/delete_flow.py
- cdp-agentkit-core/python/cdp_agentkit_core/actions/superfluid/update_flow.py
- cdp-agentkit-core/python/tests/actions/superfluid/test_create_flow.py
- cdp-agentkit-core/python/tests/actions/superfluid/test_delete_flow.py
- cdp-agentkit-core/python/tests/actions/superfluid/test_update_flow.py
- Add `cdp-agentkit-core` CHANGELOG.md entry for https://github.com/coinbase/agentkit/pull/143
- `make format && make lint-fix`
> chore(AGENT-68): Superfluid Python Core Changelog

- .github/CONTRIBUTING-PYTHON.md
- .github/CONTRIBUTING-TYPESCRIPT.md
Some quick fixes based on feedback
> chore: fixes to contributing guides

- cdp-agentkit-core/typescript/CHANGELOG.md
- cdp-agentkit-core/typescript/src/actions/cdp/social/farcaster/account_details.ts
- cdp-agentkit-core/typescript/src/actions/cdp/social/farcaster/index.ts
- cdp-agentkit-core/typescript/src/actions/cdp/social/farcaster/post_cast.ts
- cdp-agentkit-core/typescript/src/tests/social_farcaster_account_details_test.ts
- cdp-agentkit-core/typescript/src/tests/social_farcaster_post_cast_test.ts
- farcaster-langchain/typescript/README.md
- farcaster-langchain/typescript/src/farcaster_toolkit.ts
- farcaster-langchain/typescript/src/tests/farcaster_toolkit_test.ts
- package-lock.json
> feat: farcaster refinements

- cdp-agentkit-core/python/CHANGELOG.md
- cdp-agentkit-core/python/docs/conf.py
- cdp-agentkit-core/python/poetry.lock
- cdp-agentkit-core/python/pyproject.toml
- cdp-agentkit-core/typescript/CHANGELOG.md
- cdp-agentkit-core/typescript/package.json
- farcaster-langchain/typescript/package.json
- package-lock.json
* release python cdp-agentkit-core 0.0.11
* release typescript cdp-agentkit-core 0.0.14
> chore: release cdp-agentkit-core

- farcaster-langchain/typescript/CHANGELOG.md
> chore: prepare `@coinbase/farcaster-langchain` changelog for release

- cdp-agentkit-core/typescript/src/tests/deploy_contract_test.ts
- cdp-agentkit-core/typescript/src/tests/deploy_nft_test.ts
- cdp-agentkit-core/typescript/src/tests/deploy_token_test.ts
- cdp-agentkit-core/typescript/src/tests/get_balance_test.ts
- cdp-agentkit-core/typescript/src/tests/get_wallet_details_test.ts
- cdp-agentkit-core/typescript/src/tests/mint_nft_test.ts
- cdp-agentkit-core/typescript/src/tests/social_twitter_account_details_test.ts
- cdp-agentkit-core/typescript/src/tests/social_twitter_post_tweet_reply_test.ts
- cdp-agentkit-core/typescript/src/tests/social_twitter_post_tweet_test.ts
- Corrected "An error has occured" to "An error has occurred."
1. **`deploy_contract_test.ts`**
2. **`deploy_nft_test.ts`**
3. **`deploy_token_test.ts`**
4. **`get_balance_test.ts`**
5. **`get_wallet_details_test.ts`**
6. **`mint_nft_test.ts`**
7. **`social_twitter_account_details_test.ts`**
8. **`social_twitter_post_tweet_reply_test.ts`**
9. **`social_twitter_post_tweet_test.ts`**
> Fix typos in Test Files

- cdp-agentkit-core/typescript/src/action_providers/cdp/README.md
- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/index.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/schemas.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/README.md
- cdp-agentkit-core/typescript/src/action_providers/erc721/constants.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/erc721ActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/erc721ActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/index.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/schemas.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/README.md
- cdp-agentkit-core/typescript/src/action_providers/farcaster/farcasterActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/farcasterActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/index.ts
- cdp-agentkit-core/typescript/src/action_providers/farcaster/schemas.ts
- cdp-agentkit-core/typescript/src/action_providers/pyth/pyth_action_provider.ts
- cdp-agentkit-core/typescript/src/action_providers/pyth/schemas.ts
- cdp-agentkit-core/typescript/src/wallet_providers/evm_wallet_provider.ts
Added action providers for CDP, Farcaster and ERC721 actions
> chore: CDP, Farcaster, ERC721 action providers

- cdp-agentkit-core/typescript/src/action_providers/erc20/README.md
- cdp-agentkit-core/typescript/src/action_providers/erc20/constants.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/erc20ActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/erc20ActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/index.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/schemas.ts
> chore: migrate erc20 action

- cdp-agentkit-core/typescript/package.json
- cdp-agentkit-core/typescript/src/action_providers/morpho/constants.ts
- cdp-agentkit-core/typescript/src/action_providers/morpho/index.ts
- cdp-agentkit-core/typescript/src/action_providers/morpho/morphoActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/morpho/morphoActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/morpho/schemas.ts
- cdp-agentkit-core/typescript/src/utils.test.ts
- cdp-agentkit-core/typescript/src/utils.ts
- package-lock.json
> 0.1.0(ts): morpho actions

- cdp-agentkit-core/typescript/src/action_providers/erc20/erc20ActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/erc20ActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/erc20/schemas.ts
- cdp-agentkit-core/typescript/src/wallet_providers/cdp_wallet_provider.ts
- cdp-agentkit-core/typescript/src/wallet_providers/evm_wallet_provider.ts
- cdp-agentkit-core/typescript/src/wallet_providers/viem_wallet_provider.ts
- cdp-agentkit-core/typescript/src/wallet_providers/wallet_provider.ts
* Adds erc20 getBalance action
> chore: migrate erc20 getBalance

- cdp-agentkit-core/typescript/src/action_providers/erc721/constants.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/erc721ActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/erc721/erc721ActionProvider.ts
* Migrate support for fetching erc-721 balance
> chore: migrate erc721 getBalance

- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.ts
> chore: fix typo

- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/cdpActionProvider.ts
- cdp-agentkit-core/typescript/src/action_providers/cdp/schemas.ts
- cdp-agentkit-core/typescript/src/agentkit.ts
- cdp-agentkit-core/typescript/src/network/network.ts
- cdp-agentkit-core/typescript/src/wallet_providers/cdp_wallet_provider.ts
- cdp-langchain/examples/chatbot-typescript/chatbot.ts
- cdp-langchain/typescript/src/index.test.ts
* Moves CDP Wallet initialization into CDP Wallet Provider class
* Adds static async initialization to AgentKit
* Adds deploy token
> chore: migrate deploy token

- cdp-agentkit-core/typescript/src/action_providers/wallet/walletActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action_providers/wallet/walletActionProvider.ts
the agent attempts to unsuccessfully convert native untils to eth. this provides the calculated value in the action reponse response.
> 0.1.0(ts): adding eth balance to wallet details

- cdp-agentkit-core/typescript/package.json
- cdp-agentkit-core/typescript/src/action_providers/action_decorator.ts
- cdp-agentkit-core/typescript/src/analytics/index.ts
- cdp-agentkit-core/typescript/src/analytics/sendAnalyticsEvent.ts
- cdp-agentkit-core/typescript/src/wallet_providers/wallet_provider.ts
- package-lock.json
- Emit metrics using the `client-analytics` package
- metric for agent initialization and for action invocation
> feat: Emit metrics

- README.md
- Add emojis to section headers
- Break up Documentation section by language
> Further polish on README

- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpWalletActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/cdpWalletActionProvider.ts
- cdp-agentkit-core/typescript/src/action-providers/cdp/schemas.ts
- cdp-agentkit-core/typescript/src/wallet-providers/cdpWalletProvider.ts
* Migrates CDP Wallet trade action
> chore: migrate trade action

- cdp-agentkit-core/typescript/src/action-providers/actionDecorator.ts
> chore: prefix action name

- cdp-agentkit-core/typescript/src/agentkit.ts
* Sets WalletActionProvider as default
> chore: set default action provider to wallet action provider

- cdp-agentkit-core/typescript/src/action-providers/wallet/schemas.ts
- cdp-agentkit-core/typescript/src/action-providers/wallet/walletActionProvider.test.ts
- cdp-agentkit-core/typescript/src/action-providers/wallet/walletActionProvider.ts
- cdp-agentkit-core/typescript/src/wallet-providers/cdpWalletProvider.ts
- cdp-agentkit-core/typescript/src/wallet-providers/viemWalletProvider.ts
- cdp-agentkit-core/typescript/src/wallet-providers/walletProvider.ts
- cdp-langchain/examples/chatbot-typescript/chatbot.ts
* migrated wallet native transfer
[x] tested locally with cdp and viem wallet providers
cdp wallet:
```
Prompt: can you transfer 0.00003 ETH to 0x5154eAE861cAc3aA757d6016babAF972341354cf
- Address: 0x349002E7213E7F7CF68a8368ca83Fd85CEC4DDB0
- Network:
- ETH Balance: 1.241036 ETH
- Native Balance: 1241035968707162614 WEI
Transferred 0.00003 ETH to 0x5154eAE861cAc3aA757d6016babAF972341354cf.
Transaction hash: 0x367401e81d2be7dc3705a80989f921a57b02a9042d1011a0d93955252afe2efe
I've successfully transferred 0.00003 ETH to the address 0x5154eAE861cAc3aA757d6016babAF972341354cf. The transaction hash is …
```
> 0.1.0(ts): wallet native token transfer

- cdp-agentkit-core/typescript/src/wallet-providers/cdpWalletProvider.ts
> 0.1.0(ts): cdp wallet provider

- .gitignore
- README.md
Fixes link to https://coinbase.github.io/agentkit/agentkit-langchain/typescript/index.html
> chore: fix link in readme

- README.md
- Fix quick start order in README.md table of contents
> chore: Fix README.md Table of Contents

- package-lock.json
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/README.md
- typescript/agentkit/package.json
- typescript/agentkit/src/agentkit.ts
- typescript/agentkit/src/index.ts
- typescript/agentkit/src/network/index.ts
- release `@coinbase/agentkit` `0.1.1`
- re-export `..../src/network/` from `.../src/index.ts`
> feat: Release AgentKit.js 0.1.1 with Network re-exported

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
Closes https://github.com/coinbase/agentkit/issues/238
> fix: include account in call to estimateGas

- .github/workflows/lint.yml
- package.json
- typescript/examples/langchain-cdp-chatbot/.prettierignore
- typescript/examples/langchain-cdp-chatbot/.prettierrc
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/.prettierignore
- typescript/examples/langchain-farcaster-chatbot/.prettierrc
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/.prettierignore
- typescript/examples/langchain-twitter-chatbot/.prettierrc
- typescript/examples/langchain-twitter-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
Adds check that will fail CI if TS code is not formatted correctly
> chore: add format check to typescript packages

- typescript/agentkit/src/action-providers/pyth/pythActionProvider.test.ts
Adds unit test for PythActionProvider.
This will close: https://github.com/coinbase/agentkit/issues/262
> chore: add unit test for python action provider

- .github/workflows/lint.yml
- .github/workflows/unit_tests.yml
- python/coinbase-agentkit/Makefile
- python/coinbase-agentkit/coinbase_agentkit/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/action_decorator.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/pyth/pyth_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/agentkit.py
- python/coinbase-agentkit/coinbase_agentkit/network.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/evm_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/wallet_provider.py
- python/coinbase-agentkit/pyth_price_example.py
- python/coinbase-agentkit/tests/test_pyth_action_provider.py
* Adds a `Makefile` to the Python agentkit package, and runs & fixes format and lint errors
* Updates GH actions to point test & lint to new folder
* Adds test for pyth
> chore: add makefile and run format and lint

- python/coinbase-agentkit/coinbase_agentkit/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/wallet_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/wallet_provider.py
- python/coinbase-agentkit/tests/action_providers/wallet/conftest.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_get_balance.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_get_details.py
migrating wallet actions for 0.1.0
```
Prompt: what are my wallet details?
- Provider: eth-account
- Address: 0x349002E7213E7F7CF68a8368ca83Fd85CEC4DDB0
- Network:
* Network ID: 8453
* Chain ID: 8453
- Native Balance: 255051616070800
Here are your wallet details:
- **Provider:** eth-account
- **Address:** 0x349002E7213E7F7CF68a8368ca83Fd85CEC4DDB0
- **Network:**
- **Protocol Family:** evm
- **Network ID:** 8453
- **Chain ID:** 8453
- **Native Balance:** 255051616070800 (in the native token of the network)
```
> 0.1.0(py): wallet

- .github/pull_request_template.md
missing checklist item and wallet support refinements
> chore: pr template additions

- python/coinbase-agentkit/coinbase_agentkit/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/validators.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/wallet_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/wallet_provider.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_native_transfer.py
- python/coinbase-agentkit/tests/wallet_providers/test_cdp_wallet_provider.py
- python/examples/langchain-cdp-chatbot/chatbot.py
CDP Wallet Provider:
```
Prompt: please transfer 0.00001 eth to 0x5154eAE861cAc3aA757d6016babAF972341354cf
- Address: 0x349002E7213E7F7CF68a8368ca83Fd85CEC4DDB0
- Network:
- Native Balance: 953359631347783406.0000000000
Successfully transferred 0.00001 native tokens to 0x5154eAE861cAc3aA757d6016babAF972341354cf.
Transaction hash: 0xffcc5fb66fd40f25af7a412025043096577d8c1e00f5fa2c95861a1ba6832a37
The transfer of 0.00001 ETH to the address 0x5154eAE861cAc3aA757d6016babAF972341354cf was successful. 
Transaction hash: **0xffcc5fb66fd40f25af7a412025043096577d8c1e00f5fa2c95861a1ba6832a37**. …
```
> 0.0.1(py): native transfer

- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/cdp_api_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/validators.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/wallet_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/eth_account_wallet_provider.py
- python/coinbase-agentkit/tests/action_providers/cdp/conftest.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_api_faucet_funds.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_cdp_api_action_provider.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_native_transfer.py
- python/coinbase-agentkit/tests/wallet_providers/test_cdp_wallet_provider.py
> chore: formatting

- python/coinbase-agentkit/coinbase_agentkit/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/basename/basename_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/basename/constants.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/basename/schemas.py
- python/coinbase-agentkit/tests/action_providers/basename/conftest.py
- python/coinbase-agentkit/tests/action_providers/basename/test_basename_action_provider.py
Migrate basename registration action
Prompt:
```
Prompt: register basename hello-from-py for 0.0001 eth
```
Output:
```
Successfully registered basename hello-from-py.basetest.eth for address 0x9Dcd61940a94c921d8CC77472ac396deB112852E
The basename "hello-from-py.basetest.eth" has been successfully registered for your address! If you need any further assistance, feel free to ask.
```
Transaction: https://sepolia.basescan.org/tx/0x077f3cf14a5e17f97508ece3d1fb7ec8bbe130321a29a3c6ac2d1e1cfd8f9af6
> chore: migrate basename

- python/coinbase-agentkit/coinbase_agentkit/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/__init__.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/morpho_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/superfluid/constants.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/superfluid/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/superfluid/superfluid_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_wallet_provider.py
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/evm_wallet_provider.py
- python/coinbase-agentkit/tests/action_providers/superfluid/test_superfluid_action_provider.py
- python/examples/langchain-cdp-chatbot/chatbot.py
Migrate Superfluid to 0.1.0 Python
> feat: Migrate Superfluid py to 0.1.0

- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/cdp_api_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/cdp_wallet_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/morpho_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/superfluid/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/superfluid/superfluid_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/twitter/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/twitter/twitter_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/wallet_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/weth/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/weth/weth_action_provider.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wow/schemas.py
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wow/wow_action_provider.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_api_address_reputation_action.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_api_faucet_funds.py
- python/coinbase-agentkit/tests/action_providers/cdp/test_cdp_wallet_action_provider.py
- python/coinbase-agentkit/tests/action_providers/superfluid/test_superfluid_action_provider.py
- python/coinbase-agentkit/tests/action_providers/twitter/test_account_details.py
- python/coinbase-agentkit/tests/action_providers/twitter/test_account_mentions.py
- python/coinbase-agentkit/tests/action_providers/twitter/test_post_tweet.py
- python/coinbase-agentkit/tests/action_providers/twitter/test_post_tweet_reply.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_get_balance.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_get_details.py
- python/coinbase-agentkit/tests/action_providers/wallet/test_native_transfer.py
- python/coinbase-agentkit/tests/action_providers/weth/test_wrap_eth.py
- python/coinbase-agentkit/tests/action_providers/wow/test_buy_token.py
- python/coinbase-agentkit/tests/action_providers/wow/test_create_token.py
- python/coinbase-agentkit/tests/action_providers/wow/test_sell_token.py
* ensuring schema class name nomenclature
> 0.1.0(py): ensure schema nomenclature

- CONTRIBUTING-PYTHON.md
- CONTRIBUTING-TYPESCRIPT.md
- CONTRIBUTING.md
- README.md
- python/coinbase-agentkit/README.md
- typescript/agentkit/README.md
* Adds readme to `python/coinbase-agenkit`
* Updates CONTRIBUTING-PYTHON.md
* Makes minor fixes in CONTRIBUTING-TYPESCRIPT.md and `typescript/agentkit/README.md`
> chore: add python agentkit readme

- python/coinbase-agentkit/coinbase_agentkit/action_providers/action_decorator.py
- python/coinbase-agentkit/coinbase_agentkit/analytics/send_analytics_event.py
- add programming language and full prefix name to metrics
> Metrics cleanup

- python/framework-extensions/langchain/poetry.lock
- python/framework-extensions/langchain/pyproject.toml
- Add published package version dep to `coinbase-agentkit-langchain` for `coinbase-agentkit`
> chore: Update coinbase-agentkit dep to use published pypi package

- README.md
- python/coinbase-agentkit/docs/index.rst
- python/framework-extensions/langchain/docs/index.rst
> chore: update index.rst

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/docs/conf.py
- python/coinbase-agentkit/pyproject.toml
chore: release coinbase-agentkit v0.1.1
> chore: release coinbase-agentkit v0.1.1

- .eslintrc.base.json
> chore: rm multiline comment eslint rule

- typescript/agentkit/CHANGELOG.md
> chore: update changelog

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/docs/conf.py
- python/coinbase-agentkit/pyproject.toml
> chore: bump coinbase-agentkit to 0.1.2

- package-lock.json
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
> chore: bump @coinbase/agentkit to 0.2.0

- package-lock.json
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
> chore: bump @coinbase/agentkit-langchain

- .github/workflows/lint.yml
- package-lock.json
This will prevent PRs from being merged when there are uncommitted changes to a lock file. It handles `package-lock.json`, as well as the various `poetry.lock` files in the repo.
See [here](https://github.com/coinbase/agentkit/actions/runs/13378816808/job/37363521677?pr=407) for example faillure.
This PR also commits previously uncommitted changes to the `package-lock.json`
> chore: lint lockfiles

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/spl/README.md
- typescript/agentkit/src/action-providers/spl/schemas.ts
- typescript/agentkit/src/action-providers/spl/splActionProvider.test.ts
- typescript/agentkit/src/action-providers/spl/splActionProvider.ts
SVM
SVM
```
Prompt: what is my spl token balance for this mint address: Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr
- Provider: solana_keypair_wallet_provider
- Address: 9V1CjejKN5gUdCrFusXq9V7W8xQ4x5JoiBF4T6QiRkYn
- Network:
* Protocol Family: svm
* Network ID: solana-devnet
* Chain ID: EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG
- Native Balance: 49997932000 LAMPORTS
Balance for 9V1CjejKN5gUdCrFusXq9V7W8xQ4x5JoiBF4T6QiRkYn is 920 tokens
Your SPL token balance for the mint address `Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr` is **920 tokens**.
```
> feat: spl token balance

- package-lock.json
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
> chore: bump @coinbase/agentkit and @coinbase/agentkit-langchain

- typescript/agentkit/README.md
> chore: add privy to svm wallet providers list

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/spl/splActionProvider.test.ts
- typescript/agentkit/src/action-providers/spl/splActionProvider.ts
incorrectly handling `TokenAccountNotFoundError`
SVM
SVM
empty wallet:
```
Prompt: what is my spl token balance for this mint address: Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr
- Provider: solana_keypair_wallet_provider
- Address: Fn8J5eQFWgWB8jDEko738Bu2bg46w7fdgfmKuAbLAnYd
- Network:
* Protocol Family: svm
* Network ID: solana-devnet
* Chain ID: EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG
- Native Balance: 0 LAMPORTS
Balance for Fn8J5eQFWgWB8jDEko738Bu2bg46w7fdgfmKuAbLAnYd is 0 tokens
Your SPL token balance for the mint address `Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr` is 0 tokens.
```
token wallet:
```
Prompt: what is my spl token balance for this mint address: …
```
> fix: spl getBalance action error handling

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/index.ts
- typescript/agentkit/src/action-providers/wow/constants.ts
- typescript/agentkit/src/action-providers/wow/wowActionProvider.test.ts
- typescript/agentkit/src/action-providers/wow/wowActionProvider.ts
create:
```
Prompt: please create WoW token called AgentCoin with symbol Agent with default metadata
Created WoW ERC20 memecoin AgentCoin with symbol Agent on network base-sepolia.
Transaction hash: 0x2c968d095bed88d30902bfc790814b7817f76f86d579c702939ae58bf019c009
The WoW ERC20 memecoin "AgentCoin" with the symbol "Agent" has been successfully created on the Base Sepolia network.
Transaction hash: **0x2c968d095bed88d30902bfc790814b7817f76f86d579c702939ae58bf019c009**.
```
buy:
```
Prompt: please buy 0.0000001 WETH of AGENT at 0x4efB890215Bc59c8FA7e71092d9a106d9b3567c2
Purchased WoW ERC20 memecoin with transaction hash: 0xbd59d950b3f3f00ac4a01421b970639aaaecddc2dc57bb6487a29bea39b88cc7
You …
```
> fix(ts): wow exports, supported networks, and response

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/analytics/sendAnalyticsEvent.ts
> chore(ts): add agentkit_language to events

- typescript/agentkit/README.md
> chore: update typescript/agentkit/README.md

- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/src/action-providers/jupiter/jupiterActionProvider.test.ts
- typescript/agentkit/src/action-providers/jupiter/jupiterActionProvider.ts
```
Prompt: please use the jupiter swap action to swap 1 USDC (mint is EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v) to USDT (mint is Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB), i have the funds available
- Provider: solana_keypair_wallet_provider
- Address: 9V1CjejKN5gUdCrFusXq9V7W8xQ4x5JoiBF4T6QiRkYn
- Network:
* Protocol Family: svm
* Network ID: solana-mainnet
* Chain ID: 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d
- Native Balance: 13927073 LAMPORTS
It looks like you are on the Solana mainnet, but the faucet and some operations are only allowed on the Solana devnet. Unfortunately, I can't perform token swaps on the mainnet directly.
Please provide your wallet details again or send me some USDC from another wallet, and I will …
```
> fix(ts): jupiter network support

- package-lock.json
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
> chore: bump @coinbase/agentkit and @coinbase/agentkit-langchain to 0.2.2

- .github/labeler.yml
> chore: adjust labeler

- typescript/examples/langchain-solana-chatbot/chatbot.ts
adjusting solana example wallet persistence
> fix: solana example wallet persistence

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/docs/conf.py
- python/coinbase-agentkit/pyproject.toml
locked changelog, bumped version
> release(py): 0.1.3

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
GH issues templates
refinements and updates
*bug report:*
*feature request:*
> chore: issues templates updates

- README.md
Updated the base repo's README to recommend the CLI tools for getting started
> chore: added quickstart cli to readme

- typescript/.changeset/slimy-pianos-hear.md
- typescript/agentkit/README.md
- typescript/agentkit/src/action-providers/compound/README.md
- typescript/agentkit/src/action-providers/compound/compoundActionProvider.test.ts
- typescript/agentkit/src/action-providers/compound/compoundActionProvider.ts
- typescript/agentkit/src/action-providers/compound/constants.ts
- typescript/agentkit/src/action-providers/compound/index.ts
- typescript/agentkit/src/action-providers/compound/schemas.ts
- typescript/agentkit/src/action-providers/compound/utils.ts
- typescript/agentkit/src/action-providers/index.ts
This change add an Action Provider for Compound Finance. This allows agents to supply, borrow, repay, withdraw and get portfolio details about their position on Compound.
```
Executing: Wrap 0.0001 ETH to WETH
Wrapped ETH with transaction hash: 0xdd6c6f1f2ecd95b6e508fdaa4e503c6dd5318f26906bfa586eaebb00d029d628
I successfully wrapped 0.0001 ETH to WETH. You can view the transaction details [here](https://sepolia.basescan.org/tx/0xdd6c6f1f2ecd95b6e508fdaa4e503c6dd5318f26906bfa586eaebb00d029d628).
Executing: Supply 0.0001 WETH to Compound
Supplied 0.0001 WETH to Compound.
Transaction hash: 0x6981393f5391667b5c5acb50349d4260b0061d24cd1ea068930863d7ef7e8399
I successfully supplied 0.0001 WETH to …
```
> feat: Added Compound Finance Typescript Actions

- typescript/agentkit/README.md
> fix: updated typescript/agentkit README

- python/coinbase-agentkit/changelog.d/+24d3eed5.bugfix.md
- python/coinbase-agentkit/coinbase_agentkit/wallet_providers/cdp_wallet_provider.py
- typescript/.changeset/short-candies-carry.md
- typescript/agentkit/src/wallet-providers/cdpWalletProvider.ts
fixes for network and wallet data
tested with the python & typescript cdp langchain chatbots
> fix: cdp wallet data network

- typescript/.changeset/plenty-cars-arrive.md
- typescript/agentkit/package.json
- typescript/framework-extensions/langchain/package.json
- typescript/package-lock.json
Bumps `@coinbase/coinbase-sdk` for v0.20.0 for support for Ed25519 API keys.
> chore: bump @coinbase/coinbase-sdk

- CONTRIBUTING-PYTHON.md
- CONTRIBUTING-TYPESCRIPT.md
> fix: typos

- typescript/agentkit/src/action-providers/alchemy/README.md
- typescript/agentkit/src/action-providers/basename/README.md
- typescript/agentkit/src/action-providers/cdp/README.md
- typescript/agentkit/src/action-providers/compound/README.md
- typescript/agentkit/src/action-providers/erc20/README.md
- typescript/agentkit/src/action-providers/erc721/README.md
- typescript/agentkit/src/action-providers/farcaster/README.md
- typescript/agentkit/src/action-providers/jupiter/README.md
- typescript/agentkit/src/action-providers/moonwell/README.md
- typescript/agentkit/src/action-providers/morpho/README.md
- typescript/agentkit/src/action-providers/pyth/README.md
- typescript/agentkit/src/action-providers/spl/README.md
- typescript/agentkit/src/action-providers/twitter/README.md
- typescript/agentkit/src/action-providers/wallet/README.md
- typescript/agentkit/src/action-providers/weth/README.md
- typescript/agentkit/src/action-providers/wow/README.md
Adds a README.md to each action provider folder, following a consistent format.
> chore: create/update typescript action provider readmes

- python/coinbase-agentkit/coinbase_agentkit/action_providers/basename/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/cdp/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/compound/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc20/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/erc721/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/morpho/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/pyth/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/superfluid/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/twitter/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wallet/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/weth/README.md
- python/coinbase-agentkit/coinbase_agentkit/action_providers/wow/README.md
Adds a README.md to each action provider folder, following a consistent format.
> chore: create/update python action provider readmes

- python/create-onchain-agent/changelog.d/503.feature.md
- python/create-onchain-agent/create_onchain_agent/cli.py
- python/create-onchain-agent/templates/chatbot/.env.local.jinja
- python/create-onchain-agent/templates/chatbot/chatbot.py.jinja
Added SmartWallet to the cli as a wallet_provider, and updated the templates to support it.
Parity with #499 
 No private key set. Expecting it to still work and create a wallet file
```
Prompt: What is your address? Also, use the faucet
- Provider: cdp_smart_wallet_provider
- Address: 0x98Bcf76Fe3410ef9Fb9330c098564b8701fc4C8F
- Network:
- Native Balance: 0
Received eth from the faucet. Transaction: https://sepolia.basescan.org/tx/0x4da761b8be5e3058a0dac0072e079bb9d41531570349246c0b8ade45b1a847f8
I received ETH from the faucet. You can view the transaction details [here](https://sepolia.basescan.org/tx/0x4da761b8be5e3058a0dac00 …
```
> feat: added smart wallet support to pipx create-onchain-agent

- typescript/examples/vercel-ai-sdk-cdp-chatbot/chatbot.ts
This PR:
* Uses the newer `gpt-4o-mini` which has more compatability
* Introduces the autonomous run mode, as standard across our chatbot examples
Now when starting the chatbot, you are prompted to select a mode:
```
npm run start
> @coinbase/cdp-vercel-ai-sdk-chatbot-example@1.0.0 start
> NODE_OPTIONS='--no-warnings' ts-node ./chatbot.ts
Starting Agent...
Available modes:
1. chat    - Interactive chat mode
2. auto    - Autonomous action mode
Choose a mode (enter number or name): 2
Starting autonomous mode...
I executed a series of interesting actions on the blockchain:
1. **Received ETH from the faucet**: I requested and successfully received some ETH on the base-sepolia network. You can view the transaction [here](https://sepolia.basescan.org/tx/0x876d94ac66ef1b7ee17211992cc6a453a4fb80b7 …
```
> chore: vercel ai chatbot fixes

- CONTRIBUTING.md
- README.md
- assets/frameworks/vercel.svg
- typescript/README.md
- typescript/framework-extensions/vercel-ai-sdk/README.md
> chore: vercel ai readme updates

- typescript/agentkit/scripts/generate-action-provider/utils.ts
fixed text from `axtion` to `action`
> fix(ts): generate-action-provider output text

- CONTRIBUTING.md
- README.md
- typescript/README.md
- typescript/framework-extensions/langchain/README.md
- typescript/framework-extensions/model-context-protocol/.eslintrc.json
- typescript/framework-extensions/model-context-protocol/.prettierignore
- typescript/framework-extensions/model-context-protocol/.prettierrc
- typescript/framework-extensions/model-context-protocol/CHANGELOG.md
- typescript/framework-extensions/model-context-protocol/README.md
- typescript/framework-extensions/model-context-protocol/jest.config.cjs
- typescript/framework-extensions/model-context-protocol/package.json
- typescript/framework-extensions/model-context-protocol/src/index.test.ts
- typescript/framework-extensions/model-context-protocol/src/index.ts
- typescript/framework-extensions/model-context-protocol/tsconfig.json
- typescript/framework-extensions/vercel-ai-sdk/README.md
- typescript/package-lock.json
- typescript/package.json
- Anthropic Model Context Protocol Support (MCP) Support
- `@coinbase/agentkit-model-context-protocol` exports a helper to convert `AgentKit` instance into executable MCP Tools
https://github.com/user-attachments/assets/50492e0e-250b-447c-b761-d285ef574b50
> feat: Model Context Protocol Extension

- .github/workflows/publish_docs.yml
- .github/workflows/publish_npm_agentkit_model_context_protocol.yml
- Publish AgentKit MCP
- Publish AgentKit MCP Docs
> chore: Publish AgentKit MCP

- typescript/framework-extensions/model-context-protocol/README.md
> chore: MCP README Typo

- README.md
- Add API References for Vercel AI SDK and MCP Extensions
> chore: Add Vercel AI SDK and MCP Docs to README

- python/coinbase-agentkit/CHANGELOG.md
- python/coinbase-agentkit/pyproject.toml
- python/create-onchain-agent/pyproject.toml
- python/framework-extensions/langchain/pyproject.toml
This PR makes some changes to the towncrier configs to fix some issues in the generated changelog that would require manual cleanup.
Towncrier can be run in draft mode to see what it will produce:
```
poetry run -- towncrier build --yes --draft
```
Output running on main:
```
- Fixed Compound borrow action (#496)
```
Output running on this branch:
```
- Fixed Compound borrow action ([#496](https://github.com/coinbase/agentkit/pull/496))
```
Additionally, the changelog title was being mangled previously, due to an incorrect usage of the `start_string` config.
> chore: update towncrier config

- .github/workflows/publish_npm_agentkit.yml
- .github/workflows/publish_npm_create_onchain_agent.yml
- .github/workflows/publish_pypi_coinbase_agentkit.yml
- .github/workflows/publish_pypi_coinbase_agentkit_langchain.yml
- .github/workflows/publish_pypi_create_onchain_agent.yml
It was bothering me that we were using different names for the same things.
> chore: update publish action names

- typescript/framework-extensions/langchain/package.json
- typescript/framework-extensions/langchain/tsconfig.json
- typescript/package-lock.json
See: https://github.com/coinbase/agentkit/pull/523
Tested in the same way as https://github.com/coinbase/agentkit/pull/523, but using langchain.
> chore(langchain): improve dependency management

- typescript/framework-extensions/model-context-protocol/package.json
- typescript/framework-extensions/model-context-protocol/tsconfig.json
- typescript/package-lock.json
See: https://github.com/coinbase/agentkit/pull/523
Tested in same way as above PR, but with an mcp-specific repo: https://github.com/0xRAG/mcp
Result:
> chore(mcp): improve dependency management

- typescript/.changeset/all-nails-cry.md
- typescript/.changeset/breezy-parks-buy.md
- typescript/.changeset/chubby-hornets-end.md
- typescript/.changeset/lovely-vans-knock.md
- typescript/.changeset/ripe-buttons-dress.md
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
- typescript/create-onchain-agent/CHANGELOG.md
- typescript/create-onchain-agent/package.json
- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-smart-wallet-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
- typescript/examples/vercel-ai-sdk-cdp-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
- typescript/framework-extensions/model-context-protocol/package.json
- typescript/framework-extensions/vercel-ai-sdk/CHANGELOG.md
- typescript/framework-extensions/vercel-ai-sdk/package.json
- typescript/package-lock.json
Release Typescript packages for `@coinbase/agentkit` version `0.3.0`
> chore: Release Typescript 0.3.0

- typescript/examples/langchain-cdp-chatbot/package.json
- typescript/examples/langchain-farcaster-chatbot/package.json
- typescript/examples/langchain-privy-chatbot/package.json
- typescript/examples/langchain-smart-wallet-chatbot/package.json
- typescript/examples/langchain-solana-chatbot/package.json
- typescript/examples/langchain-twitter-chatbot/package.json
- typescript/framework-extensions/langchain/package.json
- typescript/framework-extensions/model-context-protocol/package.json
- typescript/package-lock.json
This PR is to get users onto the new packaging strategy using a peer dependency for `@coinbase/agentkit`. Vercel doesn't need a bump here since it was previously bumped: https://github.com/coinbase/agentkit/pull/540/files#diff-84dc0689a3fcd62cb8763ea4c9c93650ae94306a0d8c77923b8f27eea22ab28eR3
> chore: bump typescript extension packages

- typescript/create-onchain-agent/templates/next/package.json
bump npm quickstart CLI template to use `0.3.0` version packages
> chore: Bump template versions in npm quickstart CLI

- typescript/framework-extensions/langchain/CHANGELOG.md
- typescript/framework-extensions/model-context-protocol/CHANGELOG.md
Adds entries since we bumped manually in https://github.com/coinbase/agentkit/pull/541
> chore: changelog exts

- .github/workflows/publish_pypi_coinbase_agentkit_openai_agents_sdk.yml
- Adds GHA to publish `coinbase-agentkit-openai-agents-sdk` framework extension
> feat: GHA Publish coinbase-agentkit-openai-agents-sdk to PyPI

- python/framework-extensions/openai-agents-sdk/CHANGELOG.md
- python/framework-extensions/openai-agents-sdk/changelog.d/+6f3c7e1c.feature.md
generated changelog changes via towncrier
> chore: OpenAI Agents SDK - Initial release changelog

- README.md
> chore: added a new badge

- python/coinbase-agentkit/README.md
Hi! Fixed broken links for the **CdpWalletProvider** and **EthAccountWalletProvider** references.  
The paths were incorrect due to an inconsistency in the repository structure, and they have now been updated.
> docs: update dead links

- python/create-onchain-agent/CHANGELOG.md
- python/framework-extensions/langchain/CHANGELOG.md
- python/framework-extensions/openai-agents-sdk/CHANGELOG.md
This was added to `coinbase-agentkit` but is missing from the other packages.
> chore: add towncrier release notes starting point

- typescript/examples/model-context-protocol-cdp-server/package.json
- typescript/package-lock.json
> chore: update mcp example package.json

- python/scripts/README.md
- python/scripts/version.py
- python/scripts/version.sh
Adds a script to automatically consume towncrier changelogs and bump affected package versions. It should be run from the `python` folder like so: `./scripts/version.sh`
I tested this by adding fake changelogs to cover different bump scenarios:
* no version bump (no changes)
* bugfix only (patch change)
* feature only (minor change)
* bugfix & feature (minor change)
> chore: add python bump scripts

- .github/workflows/publish_nightly.yml
- .github/workflows/publish_npm_manual.yml
- .github/workflows/version_publish_npm.yml
Uses GH Action Environments to lock down which branches can access publishing secrets (main only).
> chore: use gh action environments

- README.md
> fix contributing link in readme

- .github/workflows/publish_nightly.yml
- .github/workflows/publish_pypi_coinbase_agentkit.yml
- .github/workflows/publish_pypi_coinbase_agentkit_langchain.yml
- .github/workflows/publish_pypi_coinbase_agentkit_openai_agents_sdk.yml
- .github/workflows/publish_pypi_create_onchain_agent.yml
Uses [Trusted Publishing](https://docs.pypi.org/trusted-publishers/using-a-publisher/). This allows us to remove the `PYPI_API_TOKEN`, which will be done after verifying the changes work.
> chore(pypi): use trusted publishing

- .github/workflows/publish_nightly.yml
Fixes [this error](https://github.com/coinbase/agentkit/actions/runs/14045914085/job/39326607458)
> chore(pypi): fix nightly

- python/examples/openai-agents-sdk-cdp-chatbot/poetry.lock
- python/framework-extensions/openai-agents-sdk/changelog.d/609.feature.md
- python/framework-extensions/openai-agents-sdk/poetry.lock
- python/framework-extensions/openai-agents-sdk/pyproject.toml
Bumps openai-agents to v0.0.6
Bumped openai chatbot and verified the chatbot still boots up and works.
> chore(py): bump openai-agents to v0.0.6

- CONTRIBUTING-PYTHON.md
- CONTRIBUTING-TYPESCRIPT.md
- RELEASE.md
Moves release instructions into RELEASE.md
> chore: add RELEASE.md

- .github/workflows/publish_nightly.yml
Changesets can do this for us: https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md
> chore: use changesets to publish nightlies

- .github/workflows/publish_nightly.yml
This PR:
* Fixes the pnpm workflow by moving the git checkout action into the job workflow
> chore(ts): nightly improvement

- typescript/create-onchain-agent/templates/mcp/package.json
- typescript/create-onchain-agent/templates/next/package.json
> chore: fix templates versions

- .github/workflows/publish_pypi_coinbase_agentkit.yml
- .github/workflows/publish_pypi_coinbase_agentkit_langchain.yml
- .github/workflows/publish_pypi_coinbase_agentkit_openai_agents_sdk.yml
- .github/workflows/publish_pypi_create_onchain_agent.yml
- RELEASE.md
- python/scripts/version.sh
This PR:
* Brings back `version.sh` to automate the process of running `towncrier` in each package
* Configures the `github-action[bot]` user ([see here](https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token)) to correctly push a tag on package release
> chore: fix python release

- typescript/create-onchain-agent/README.md
fix: added manual install step to readme if agentkit cli is not found
> fix: added manual install step to readme if agentkit cli is not found

- python/scripts/version.sh
chore: migrated version script from poetry to uv
> chore: migrated version script from poetry to uv

- python/create-onchain-agent/CHANGELOG.md
- python/create-onchain-agent/pyproject.toml
- python/create-onchain-agent/uv.lock
> chore: python version package

- typescript/.changeset/wild-wolves-count.md
- typescript/create-onchain-agent/templates/mcp/package.json
- typescript/create-onchain-agent/templates/next/package.json
- typescript/pnpm-lock.yaml
depp: bumped agentkit dependency to 0.6.0 in templates
> depp: bumped agentkit dependency to 0.6.0 in templates

- python/examples/openai-agents-sdk-cdp-chatbot/.env.local
- python/examples/openai-agents-sdk-cdp-chatbot/Makefile
- python/examples/openai-agents-sdk-cdp-chatbot/README.md
- python/examples/openai-agents-sdk-cdp-chatbot/chatbot.py
- python/examples/openai-agents-sdk-cdp-chatbot/pyproject.toml
- python/examples/openai-agents-sdk-cdp-chatbot/uv.lock
- python/examples/openai-agents-sdk-smart-wallet-chatbot/chatbot.py
Added CDP SDK capabilities for OpenAI SDK chatbot.
> Added openai-agent-sdk-smart-wallet-chatbot

- python/coinbase-agentkit/coinbase_agentkit/action_providers/hyperboliclabs/README.md
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- python/coinbase-agentkit/README.md
Branch master was renamed to main so we need to update link
> chore: update link to CONTRIBUTING.md

- python/create-onchain-agent/CHANGELOG.md
- python/create-onchain-agent/changelog.d/705.feature.md
- python/create-onchain-agent/pyproject.toml
- python/create-onchain-agent/templates/beginner/pyproject.toml.jinja
- python/create-onchain-agent/templates/chatbot/pyproject.toml.jinja
- python/create-onchain-agent/uv.lock
- python/examples/langchain-cdp-server-chatbot/uv.lock
- python/examples/langchain-cdp-smart-wallet-chatbot/uv.lock
- python/examples/langchain-eth-account-chatbot/uv.lock
- python/examples/langchain-nillion-secretvault-chatbot/uv.lock
- python/examples/langchain-twitter-chatbot/uv.lock
- python/examples/openai-agents-sdk-cdp-chatbot/uv.lock
- python/examples/openai-agents-sdk-cdp-voice-chatbot/uv.lock
- python/examples/openai-agents-sdk-smart-wallet-chatbot/uv.lock
- python/framework-extensions/langchain/CHANGELOG.md
- python/framework-extensions/langchain/changelog.d/705.feature.md
- python/framework-extensions/langchain/docs/conf.py
- python/framework-extensions/langchain/pyproject.toml
- python/framework-extensions/langchain/uv.lock
- python/framework-extensions/openai-agents-sdk/CHANGELOG.md
- python/framework-extensions/openai-agents-sdk/changelog.d/705.feature.md
- python/framework-extensions/openai-agents-sdk/pyproject.toml
- python/framework-extensions/openai-agents-sdk/uv.lock
chore: version python packages
> chore: version python packages

- typescript/.changeset/vast-waves-own.md
- typescript/agentkit/CHANGELOG.md
- typescript/agentkit/package.json
Hijacked #717 and signed the commits
> chore: version typescript packages

- python/create-onchain-agent/create_onchain_agent/cli.py
The Python CLI has to download `/templates` from github. However, reading directly from main often lead to caching issues that can last days. During this period, new cli code runs on old templates, causing bugs.
This PR fixes it by downloading via the latest commit, rather than `main`. Caching still exists, but the caching for a commit hash will never be stale.
> fix: ensure templates download does not hit stale main cache

- python/create-onchain-agent/templates/chatbot/pyproject.toml.jinja
feat: update dependency relationship in chatbot template
> feat: update dependency relationship in chatbot template

- python/create-onchain-agent/CHANGELOG.md
hey! fixed error
`persistance` - `persistence`
> fix error `persistance`  to  `persistence` CHANGELOG.md

- package-lock.json
- typescript/.changeset/busy-times-enjoy.md
- typescript/agentkit/src/action-providers/vaultsfyi/README.md
- typescript/agentkit/src/action-providers/vaultsfyi/api/historicalData.ts
- typescript/agentkit/src/action-providers/vaultsfyi/api/vaults.ts
- typescript/agentkit/src/action-providers/vaultsfyi/schemas.ts
- typescript/agentkit/src/action-providers/vaultsfyi/utils.ts
- typescript/agentkit/src/action-providers/vaultsfyi/vaultsfyiActionProvider.test.ts
- typescript/agentkit/src/action-providers/vaultsfyi/vaultsfyiActionProvider.ts
This introduces a bunch of improvements for the vaults.fyi provider. This includes:
- New action: Vault details - returns detailed data for a single vault.
- New action: Vault historical data - returns vaults APY and TVL for a given date.
- Added APY range param for vault related queries. Agent can now choose to fetch 1, 7 or 30 day moving average APY.
- Handling empty strings for optional params. I noticed LLMs like to use empty strings instead of omitting fields.
- Bug fixes.
I added unit tests and tested it manually.
> Improve vaults.fyi provider

- typescript/create-onchain-agent/templates/mcp/package.json
- typescript/create-onchain-agent/templates/next/package.json
Missed bumping depps in CLI templates
> feat: bump cli template depps

- typescript/.changeset/nice-ducks-search.md
- typescript/.changeset/poor-phones-hide.md
- typescript/.changeset/violet-breads-kneel.md
Fixing minor to patch in changesets
> fix: changed changeset from minor to patch

- CONTRIBUTING-PYTHON.md
- CONTRIBUTING-TYPESCRIPT.md
- CONTRIBUTING.md
- README.md
- typescript/create-onchain-agent/README.md
A few docs fixes:
- Updates examples/framework extensions in READMEs  
- Adds commit signing info to contributing guide
- Improves changeset instructions
- Node.js v18.x -> Node.js v22.x
> update readme/contributing guides

- python/coinbase-agentkit/README.md
in `CdpSmartWalletProviderConfig` letter `c` was missed. 
> chore: fix typo in readme

- .github/workflows/publish_pypi_coinbase_agentkit_autogen.yml
- .github/workflows/publish_pypi_coinbase_agentkit_pydantic_ai.yml
- python/scripts/get_packages_to_tag.py
- python/scripts/utils/package_definitions.py
Added publishing workflows for #803 and #830, as well as updated the scripts to include the missing frameworks
> feat: publishing workflows for pydantic ai and autogen framework extensions

- typescript/.changeset/some-comics-visit.md
- typescript/create-onchain-agent/templates/mcp/_gitignore
- typescript/create-onchain-agent/templates/mcp/package.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/cdp/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/cdp/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/smart/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/evm/smart/getAgentKit.ts
- typescript/create-onchain-agent/templates/mcp/src/agentkit/svm/cdp/claude_desktop_config.json
- typescript/create-onchain-agent/templates/mcp/src/agentkit/svm/cdp/getAgentKit.ts
- typescript/create-onchain-agent/templates/next/_gitignore
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/cdp/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/next/app/api/agent/agentkit/evm/smart/prepare-agentkit.ts
- typescript/create-onchain-agent/templates/next/package.json
- typescript/create-onchain-agent/templates/next/tsconfig.json
- When creating a new project with `npm create onchain-agent@latest` no .gitignore file was included, this is dangerous as users might accidentally commit their .env 
-> added missing _gitignore files that are renamed to .gitignore as part of the template generation process (cf https://github.com/coinbase/agentkit/blob/main/typescript/create-onchain-agent/src/common/fileSystem.ts) 
- Updated agentkit etc versions to latest
- Bumped node/next versions
- Aligned mcp templates with new cdp v2 wallet patters removing privatekey config in favor of address
> fix: Added gitignore to templates and various bug fixes

- typescript/.changeset/empty-baths-send.md
- typescript/agentkit/package.json
- typescript/agentkit/src/action-providers/x402/README.md
- typescript/agentkit/src/action-providers/x402/utils.ts
- typescript/agentkit/src/action-providers/x402/x402ActionProvider.test.ts
- typescript/agentkit/src/action-providers/x402/x402ActionProvider.ts
- typescript/agentkit/src/wallet-providers/cdpSolanaWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/cdpSolanaWalletProvider.ts
- typescript/agentkit/src/wallet-providers/privySvmWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/privySvmWalletProvider.ts
- typescript/agentkit/src/wallet-providers/solanaKeypairWalletProvider.ts
- typescript/agentkit/src/wallet-providers/svmWalletProvider.test.ts
- typescript/agentkit/src/wallet-providers/svmWalletProvider.ts
- typescript/examples/langchain-cdp-chatbot/chatbot.ts
- typescript/examples/langchain-solana-chatbot/chatbot.ts
- typescript/pnpm-lock.yaml
Implements svm support for the x402 action provider
-> requires new `@solana/kit` dependency 
```
Chatbot: typescript/examples/langchain-solana-chatbot/chatbot.ts && typescript/examples/langchain-cdp-chatbot/chatbot.ts 
Network: Solana devnet
Setup: Fauceted with 1 USDC
Prompt: fetch https://biznews.x402.bot/news
{"status":"error_402_payment_required","acceptablePaymentOptions":[{"scheme":"exact","network":"solana-devnet","maxAmountRequired":"50000","resource":"https://biznews.x402.bot/news","description":"Returns a list of recent new articles that affect business.","mimeType":"","payTo":"D5Do2wEoae1kNu8pXPyExXMf7nPmX949LDzZnc5Y5zgd","maxTimeoutSeconds":60,"asset":"4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU","outputSchema":{"input":{"type":"http","method":"GET"}},"ext …
```
> feat: Add svm support to x402 action
